import { Hall } from "@/lib/data.type";

export const WEST_MALL: Hall = {
  id: 120,
  name: "سالن مال غربی",
  capacity: 150,
  city: "تهران",
  seatSections: [
    {
      id: 1,
      seatByRow: {
        "1": [
          null,
          null,
          {
            id: 1,
            rowNumber: 1,
            seatNumber: 1,
            seatPrice: 100000,
            status: "booked",
          },
          {
            id: 2,
            rowNumber: 1,
            seatNumber: 2,
            seatPrice: 100000,
            status: "booked",
          },
          {
            id: 3,
            rowNumber: 1,
            seatNumber: 3,
            seatPrice: 100000,
            status: "booked",
          },
          {
            id: 4,
            rowNumber: 1,
            seatNumber: 4,
            seatPrice: 100000,
            status: "booked",
          },
          {
            id: 5,
            rowNumber: 1,
            seatNumber: 5,
            seatPrice: 100000,
            status: "booked",
          },
          {
            id: 6,
            rowNumber: 1,
            seatNumber: 6,
            seatPrice: 100000,
            status: "booked",
          },
          {
            id: 7,
            rowNumber: 1,
            seatNumber: 7,
            seatPrice: 100000,
            status: "booked",
          },
          {
            id: 8,
            rowNumber: 1,
            seatNumber: 8,
            seatPrice: 100000,
            status: "booked",
          },
        ],
        "2": [
          {
            id: 9,
            rowNumber: 2,
            seatNumber: 1,
            seatPrice: 100000,
            status: "free",
          },
          {
            id: 10,
            rowNumber: 2,
            seatNumber: 2,
            seatPrice: 100000,
            status: "free",
          },
          {
            id: 11,
            rowNumber: 2,
            seatNumber: 3,
            seatPrice: 100000,
            status: "free",
          },
          {
            id: 12,
            rowNumber: 2,
            seatNumber: 4,
            seatPrice: 100000,
            status: "free",
          },
          {
            id: 13,
            rowNumber: 2,
            seatNumber: 5,
            seatPrice: 100000,
            status: "free",
          },
          {
            id: 14,
            rowNumber: 2,
            seatNumber: 6,
            seatPrice: 100000,
            status: "free",
          },
          {
            id: 15,
            rowNumber: 2,
            seatNumber: 7,
            seatPrice: 100000,
            status: "free",
          },
          {
            id: 16,
            rowNumber: 2,
            seatNumber: 8,
            seatPrice: 100000,
            status: "free",
          },
        ],
        "3": [
          {
            id: 17,
            rowNumber: 3,
            seatNumber: 1,
            seatPrice: 100000,
            status: "free",
          },
          {
            id: 18,
            rowNumber: 3,
            seatNumber: 2,
            seatPrice: 100000,
            status: "free",
          },
          {
            id: 19,
            rowNumber: 3,
            seatNumber: 3,
            seatPrice: 100000,
            status: "free",
          },
          {
            id: 20,
            rowNumber: 3,
            seatNumber: 4,
            seatPrice: 100000,
            status: "free",
          },
          {
            id: 21,
            rowNumber: 3,
            seatNumber: 5,
            seatPrice: 100000,
            status: "pending",
          },
          {
            id: 22,
            rowNumber: 3,
            seatNumber: 6,
            seatPrice: 100000,
            status: "pending",
          },
          {
            id: 23,
            rowNumber: 3,
            seatNumber: 7,
            seatPrice: 100000,
            status: "free",
          },
          {
            id: 24,
            rowNumber: 3,
            seatNumber: 8,
            seatPrice: 100000,
            status: "free",
          },
        ],
      },
    },
    {
      id: 2,
      seatByRow: {
        "1": [
          {
            id: 25,
            rowNumber: 1,
            seatNumber: 9,
            seatPrice: 100000,
            status: "booked",
          },
          {
            id: 26,
            rowNumber: 1,
            seatNumber: 10,
            seatPrice: 100000,
            status: "booked",
          },
          {
            id: 27,
            rowNumber: 1,
            seatNumber: 11,
            seatPrice: 100000,
            status: "booked",
          },
          {
            id: 28,
            rowNumber: 1,
            seatNumber: 12,
            seatPrice: 100000,
            status: "booked",
          },
          {
            id: 29,
            rowNumber: 1,
            seatNumber: 13,
            seatPrice: 100000,
            status: "booked",
          },
          {
            id: 30,
            rowNumber: 1,
            seatNumber: 14,
            seatPrice: 100000,
            status: "booked",
          },
          {
            id: 31,
            rowNumber: 1,
            seatNumber: 15,
            seatPrice: 100000,
            status: "booked",
          },
          {
            id: 32,
            rowNumber: 1,
            seatNumber: 16,
            seatPrice: 100000,
            status: "booked",
          },
          {
            id: 33,
            rowNumber: 1,
            seatNumber: 17,
            seatPrice: 100000,
            status: "booked",
          },
          {
            id: 34,
            rowNumber: 1,
            seatNumber: 18,
            seatPrice: 100000,
            status: "booked",
          },
          {
            id: 35,
            rowNumber: 1,
            seatNumber: 19,
            seatPrice: 100000,
            status: "booked",
          },
          {
            id: 36,
            rowNumber: 1,
            seatNumber: 20,
            seatPrice: 100000,
            status: "booked",
          },
        ],
        "2": [
          null,
          null,
          {
            id: 37,
            rowNumber: 2,
            seatNumber: 9,
            seatPrice: 100000,
            status: "free",
          },
          {
            id: 38,
            rowNumber: 2,
            seatNumber: 10,
            seatPrice: 100000,
            status: "free",
          },
          {
            id: 39,
            rowNumber: 2,
            seatNumber: 11,
            seatPrice: 100000,
            status: "free",
          },
          {
            id: 40,
            rowNumber: 2,
            seatNumber: 12,
            seatPrice: 100000,
            status: "free",
          },
          {
            id: 41,
            rowNumber: 2,
            seatNumber: 13,
            seatPrice: 100000,
            status: "free",
          },
          {
            id: 42,
            rowNumber: 2,
            seatNumber: 14,
            seatPrice: 100000,
            status: "free",
          },
          {
            id: 43,
            rowNumber: 2,
            seatNumber: 15,
            seatPrice: 100000,
            status: "booked",
          },
          {
            id: 44,
            rowNumber: 2,
            seatNumber: 16,
            seatPrice: 100000,
            status: "booked",
          },
        ],
        "3": [
          null,
          null,
          {
            id: 45,
            rowNumber: 3,
            seatNumber: 9,
            seatPrice: 100000,
            status: "booked",
          },
          {
            id: 46,
            rowNumber: 3,
            seatNumber: 10,
            seatPrice: 100000,
            status: "booked",
          },
          {
            id: 47,
            rowNumber: 3,
            seatNumber: 11,
            seatPrice: 100000,
            status: "booked",
          },
          {
            id: 48,
            rowNumber: 3,
            seatNumber: 12,
            seatPrice: 100000,
            status: "free",
          },
          {
            id: 49,
            rowNumber: 3,
            seatNumber: 13,
            seatPrice: 100000,
            status: "free",
          },
          {
            id: 50,
            rowNumber: 3,
            seatNumber: 14,
            seatPrice: 100000,
            status: "free",
          },
          {
            id: 51,
            rowNumber: 3,
            seatNumber: 15,
            seatPrice: 100000,
            status: "free",
          },
          {
            id: 52,
            rowNumber: 3,
            seatNumber: 16,
            seatPrice: 100000,
            status: "free",
          },
        ],
      },
    },
    {
      id: 3,
      seatByRow: {
        "1": [
          null,
          null,
          {
            id: 53,
            rowNumber: 1,
            seatNumber: 21,
            seatPrice: 100000,
            status: "booked",
          },
          {
            id: 54,
            rowNumber: 1,
            seatNumber: 22,
            seatPrice: 100000,
            status: "booked",
          },
          {
            id: 55,
            rowNumber: 1,
            seatNumber: 23,
            seatPrice: 100000,
            status: "booked",
          },
          {
            id: 56,
            rowNumber: 1,
            seatNumber: 24,
            seatPrice: 100000,
            status: "booked",
          },
          {
            id: 57,
            rowNumber: 1,
            seatNumber: 25,
            seatPrice: 100000,
            status: "booked",
          },
          {
            id: 58,
            rowNumber: 1,
            seatNumber: 26,
            seatPrice: 100000,
            status: "booked",
          },
          {
            id: 59,
            rowNumber: 1,
            seatNumber: 27,
            seatPrice: 100000,
            status: "booked",
          },
          {
            id: 60,
            rowNumber: 1,
            seatNumber: 28,
            seatPrice: 100000,
            status: "booked",
          },
        ],
        "2": [
          null,
          null,
          null,
          null,
          {
            id: 61,
            rowNumber: 2,
            seatNumber: 18,
            seatPrice: 100000,
            status: "free",
          },
          {
            id: 62,
            rowNumber: 2,
            seatNumber: 19,
            seatPrice: 100000,
            status: "free",
          },
          {
            id: 63,
            rowNumber: 2,
            seatNumber: 20,
            seatPrice: 100000,
            status: "free",
          },
          {
            id: 64,
            rowNumber: 2,
            seatNumber: 21,
            seatPrice: 100000,
            status: "free",
          },
          {
            id: 65,
            rowNumber: 2,
            seatNumber: 22,
            seatPrice: 100000,
            status: "free",
          },
          {
            id: 66,
            rowNumber: 2,
            seatNumber: 23,
            seatPrice: 100000,
            status: "free",
          },
          {
            id: 67,
            rowNumber: 2,
            seatNumber: 24,
            seatPrice: 100000,
            status: "free",
          },
          {
            id: 68,
            rowNumber: 2,
            seatNumber: 25,
            seatPrice: 100000,
            status: "free",
          },
        ],
        "3": [
          null,
          null,
          null,
          null,
          {
            id: 69,
            rowNumber: 3,
            seatNumber: 18,
            seatPrice: 100000,
            status: "free",
          },
          {
            id: 70,
            rowNumber: 3,
            seatNumber: 19,
            seatPrice: 100000,
            status: "free",
          },
          {
            id: 71,
            rowNumber: 3,
            seatNumber: 20,
            seatPrice: 100000,
            status: "free",
          },
          {
            id: 72,
            rowNumber: 3,
            seatNumber: 21,
            seatPrice: 100000,
            status: "free",
          },
          {
            id: 73,
            rowNumber: 3,
            seatNumber: 22,
            seatPrice: 100000,
            status: "free",
          },
          {
            id: 74,
            rowNumber: 3,
            seatNumber: 23,
            seatPrice: 100000,
            status: "free",
          },
          {
            id: 75,
            rowNumber: 3,
            seatNumber: 24,
            seatPrice: 100000,
            status: "free",
          },
          {
            id: 76,
            rowNumber: 3,
            seatNumber: 25,
            seatPrice: 100000,
            status: "free",
          },
        ],
      },
    },
  ],
};

// export const MILAD_NATIONAL_HALL: Hall = {
//   id: 111,
//   name: "سالن میلاد نمایشگاه بین المللی",
//   capacity: 200,
//   city: "تهران",
// };
//
// export const SHAHRZAD_THEATER: Hall = {
//   id: 112,
//   name: "پردیس تئاتر شهرزاد",
//   capacity: 450,
//   city: "تهران",
// };
//
// export const CENTRAL_THEATER: Hall = {
//   id: 113,
//   name: "سالن تئاتر مرکزی",
//   capacity: 150,
//   city: "تهران",
// };
//
// export const CENTRAL_HALL: Hall = {
//   id: 114,
//   name: "تالار مرکزی",
//   capacity: 300,
//   city: "شیراز",
// };
//
// export const MUSICAL_HALL: Hall = {
//   id: 115,
//   name: "سالن اجرای موسیقی",
//   capacity: 250,
//   city: "کرج",
// };
//
// export const CITY_THEATER: Hall = {
//   id: 116,
//   name: "سالن تئاتر شهر",
//   capacity: 200,
//   city: "اصفهان",
// };
//
// export const CENTRAL_MUSIC_HALL: Hall = {
//   id: 117,
//   name: "سالن موسیقی مرکزی",
//   capacity: 320,
//   city: "اصفهان",
// };
//
// export const CITY_MAIN_HALL: Hall = {
//   id: 118,
//   name: "تالار اصلی شهر",
//   capacity: 560,
//   city: "رشت",
// };
//
// export const MUNICIPALITY_HALL: Hall = {
//   id: 119,
//   name: "سالن شهرداری",
//   capacity: 300,
//   city: "گرگان",
// };
//
// export const BIG_CITY_HALL: Hall = {
//   id: 121,
//   name: "تالار بزرگ شهر",
//   capacity: 400,
//   city: "قزوین",
// };
