import { Hall } from "@/lib/data.type";

export const WEST_MALL_Prices = {
  PRICE_ROW_1: 1100000,
  PRICE_ROW_2: 1100000,
  PRICE_ROW_3: 800000,
  PRICE_ROW_4: 800000,
  PRICE_ROW_5: 800000,
  PRICE_ROW_6: 800000,
  PRICE_ROW_7: 600000,
  PRICE_ROW_8: 600000,
  PRICE_ROW_9: 600000,
  PRICE_ROW_10: 600000,
};

export const WEST_MALL: Hall = {
  id: 120,
  name: "سالن مال غربی",
  capacity: 222,
  city: "تهران",
  seatSections: [
    {
      id: 1,
      seatByRow: {
        "1": [
          null,
          null,
          {
            id: 3,
            rowNumber: 1,
            seatNumber: 1,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_1,
            status: "free",
          },
          {
            id: 4,
            rowNumber: 1,
            seatNumber: 2,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_1,
            status: "free",
          },
          {
            id: 5,
            rowNumber: 1,
            seatNumber: 3,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_1,
            status: "booked",
          },
          {
            id: 6,
            rowNumber: 1,
            seatNumber: 4,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_1,
            status: "booked",
          },
          {
            id: 7,
            rowNumber: 1,
            seatNumber: 5,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_1,
            status: "booked",
          },
          {
            id: 8,
            rowNumber: 1,
            seatNumber: 6,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_1,
            status: "booked",
          },
          {
            id: 9,
            rowNumber: 1,
            seatNumber: 7,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_1,
            status: "booked",
          },
          {
            id: 10,
            rowNumber: 1,
            seatNumber: 8,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_1,
            status: "booked",
          },
        ],
        "2": [
          {
            id: 11,
            rowNumber: 2,
            seatNumber: 1,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_2,
            status: "booked",
          },
          {
            id: 12,
            rowNumber: 2,
            seatNumber: 2,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_2,
            status: "booked",
          },
          {
            id: 13,
            rowNumber: 2,
            seatNumber: 3,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_2,
            status: "booked",
          },
          {
            id: 14,
            rowNumber: 2,
            seatNumber: 4,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_2,
            status: "booked",
          },
          {
            id: 15,
            rowNumber: 2,
            seatNumber: 5,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_2,
            status: "booked",
          },
          {
            id: 16,
            rowNumber: 2,
            seatNumber: 6,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_2,
            status: "booked",
          },
          {
            id: 17,
            rowNumber: 2,
            seatNumber: 7,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_2,
            status: "booked",
          },
          {
            id: 18,
            rowNumber: 2,
            seatNumber: 8,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_2,
            status: "booked",
          },
        ],
        "3": [
          {
            id: 19,
            rowNumber: 3,
            seatNumber: 1,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_3,
            status: "booked",
          },
          {
            id: 20,
            rowNumber: 3,
            seatNumber: 2,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_3,
            status: "booked",
          },
          {
            id: 21,
            rowNumber: 3,
            seatNumber: 3,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_3,
            status: "booked",
          },
          {
            id: 22,
            rowNumber: 3,
            seatNumber: 4,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_3,
            status: "booked",
          },
          {
            id: 23,
            rowNumber: 3,
            seatNumber: 5,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_3,
            status: "booked",
          },
          {
            id: 24,
            rowNumber: 3,
            seatNumber: 6,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_3,
            status: "booked",
          },
          {
            id: 25,
            rowNumber: 3,
            seatNumber: 7,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_3,
            status: "booked",
          },
          {
            id: 26,
            rowNumber: 3,
            seatNumber: 8,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_3,
            status: "booked",
          },
        ],
        "4": [
          {
            id: 27,
            rowNumber: 4,
            seatNumber: 1,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_4,
            status: "free",
          },
          {
            id: 28,
            rowNumber: 4,
            seatNumber: 2,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_4,
            status: "free",
          },
          {
            id: 29,
            rowNumber: 4,
            seatNumber: 3,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_4,
            status: "free",
          },
          {
            id: 30,
            rowNumber: 4,
            seatNumber: 4,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_4,
            status: "free",
          },
          {
            id: 31,
            rowNumber: 4,
            seatNumber: 5,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_4,
            status: "free",
          },
          {
            id: 32,
            rowNumber: 4,
            seatNumber: 6,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_4,
            status: "free",
          },
          {
            id: 33,
            rowNumber: 4,
            seatNumber: 7,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_4,
            status: "free",
          },
          {
            id: 34,
            rowNumber: 4,
            seatNumber: 8,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_4,
            status: "free",
          },
        ],
        "5": [
          {
            id: 35,
            rowNumber: 5,
            seatNumber: 1,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_5,
            status: "free",
          },
          {
            id: 36,
            rowNumber: 5,
            seatNumber: 2,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_5,
            status: "free",
          },
          {
            id: 37,
            rowNumber: 5,
            seatNumber: 3,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_5,
            status: "free",
          },
          {
            id: 38,
            rowNumber: 5,
            seatNumber: 4,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_5,
            status: "booked",
          },
          {
            id: 39,
            rowNumber: 5,
            seatNumber: 5,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_5,
            status: "booked",
          },
          {
            id: 40,
            rowNumber: 5,
            seatNumber: 6,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_5,
            status: "booked",
          },
          {
            id: 41,
            rowNumber: 5,
            seatNumber: 7,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_5,
            status: "booked",
          },
          {
            id: 42,
            rowNumber: 5,
            seatNumber: 8,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_5,
            status: "booked",
          },
        ],
        "6": [
          {
            id: 43,
            rowNumber: 6,
            seatNumber: 1,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_6,
            status: "free",
          },
          {
            id: 44,
            rowNumber: 6,
            seatNumber: 2,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_6,
            status: "free",
          },
          {
            id: 45,
            rowNumber: 6,
            seatNumber: 3,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_6,
            status: "free",
          },
          {
            id: 46,
            rowNumber: 6,
            seatNumber: 4,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_6,
            status: "free",
          },
          {
            id: 47,
            rowNumber: 6,
            seatNumber: 5,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_6,
            status: "free",
          },
          {
            id: 48,
            rowNumber: 6,
            seatNumber: 6,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_6,
            status: "free",
          },
          {
            id: 49,
            rowNumber: 6,
            seatNumber: 7,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_6,
            status: "free",
          },
          {
            id: 50,
            rowNumber: 6,
            seatNumber: 8,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_6,
            status: "free",
          },
        ],
        "7": [
          {
            id: 51,
            rowNumber: 7,
            seatNumber: 1,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_7,
            status: "free",
          },
          {
            id: 52,
            rowNumber: 7,
            seatNumber: 2,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_7,
            status: "free",
          },
          {
            id: 53,
            rowNumber: 7,
            seatNumber: 3,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_7,
            status: "free",
          },
          {
            id: 54,
            rowNumber: 7,
            seatNumber: 4,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_7,
            status: "free",
          },
          {
            id: 55,
            rowNumber: 7,
            seatNumber: 5,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_7,
            status: "free",
          },
          {
            id: 56,
            rowNumber: 7,
            seatNumber: 6,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_7,
            status: "free",
          },
          {
            id: 57,
            rowNumber: 7,
            seatNumber: 7,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_7,
            status: "free",
          },
          {
            id: 58,
            rowNumber: 7,
            seatNumber: 8,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_7,
            status: "free",
          },
        ],
        "8": [
          {
            id: 59,
            rowNumber: 8,
            seatNumber: 1,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_8,
            status: "free",
          },
          {
            id: 60,
            rowNumber: 8,
            seatNumber: 2,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_8,
            status: "free",
          },
          {
            id: 61,
            rowNumber: 8,
            seatNumber: 3,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_8,
            status: "free",
          },
          {
            id: 62,
            rowNumber: 8,
            seatNumber: 4,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_8,
            status: "booked",
          },
          {
            id: 63,
            rowNumber: 8,
            seatNumber: 5,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_8,
            status: "booked",
          },
          {
            id: 64,
            rowNumber: 8,
            seatNumber: 6,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_8,
            status: "booked",
          },
          {
            id: 65,
            rowNumber: 8,
            seatNumber: 7,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_8,
            status: "free",
          },
          {
            id: 66,
            rowNumber: 8,
            seatNumber: 8,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_8,
            status: "free",
          },
        ],
        "9": [
          {
            id: 67,
            rowNumber: 9,
            seatNumber: 1,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_9,
            status: "free",
          },
          {
            id: 68,
            rowNumber: 9,
            seatNumber: 2,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_9,
            status: "free",
          },
          {
            id: 69,
            rowNumber: 9,
            seatNumber: 3,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_9,
            status: "free",
          },
          {
            id: 70,
            rowNumber: 9,
            seatNumber: 4,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_9,
            status: "free",
          },
          {
            id: 71,
            rowNumber: 9,
            seatNumber: 5,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_9,
            status: "free",
          },
          {
            id: 72,
            rowNumber: 3,
            seatNumber: 6,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_9,
            status: "free",
          },
          {
            id: 73,
            rowNumber: 9,
            seatNumber: 7,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_9,
            status: "free",
          },
          {
            id: 74,
            rowNumber: 9,
            seatNumber: 8,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_9,
            status: "free",
          },
        ],
        "10": [
          {
            id: 75,
            rowNumber: 10,
            seatNumber: 1,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_10,
            status: "nonSale",
          },
          {
            id: 76,
            rowNumber: 10,
            seatNumber: 2,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_10,
            status: "nonSale",
          },
          {
            id: 77,
            rowNumber: 10,
            seatNumber: 3,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_10,
            status: "nonSale",
          },
          {
            id: 78,
            rowNumber: 10,
            seatNumber: 4,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_10,
            status: "nonSale",
          },
          {
            id: 79,
            rowNumber: 10,
            seatNumber: 5,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_10,
            status: "nonSale",
          },
          {
            id: 80,
            rowNumber: 10,
            seatNumber: 6,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_10,
            status: "nonSale",
          },
          {
            id: 81,
            rowNumber: 10,
            seatNumber: 7,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_10,
            status: "nonSale",
          },
          {
            id: 82,
            rowNumber: 10,
            seatNumber: 8,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_10,
            status: "nonSale",
          },
        ],
      },
    },
    {
      id: 2,
      seatByRow: {
        "1": [
          null,
          {
            id: 84,
            rowNumber: 1,
            seatNumber: 9,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_1,
            status: "booked",
          },
          {
            id: 85,
            rowNumber: 1,
            seatNumber: 10,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_1,
            status: "booked",
          },
          {
            id: 86,
            rowNumber: 1,
            seatNumber: 11,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_1,
            status: "booked",
          },
          {
            id: 87,
            rowNumber: 1,
            seatNumber: 12,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_1,
            status: "booked",
          },
          {
            id: 88,
            rowNumber: 1,
            seatNumber: 13,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_1,
            status: "booked",
          },
          {
            id: 89,
            rowNumber: 1,
            seatNumber: 14,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_1,
            status: "booked",
          },
          {
            id: 90,
            rowNumber: 1,
            seatNumber: 15,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_1,
            status: "booked",
          },
          {
            id: 91,
            rowNumber: 1,
            seatNumber: 16,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_1,
            status: "booked",
          },
          {
            id: 92,
            rowNumber: 1,
            seatNumber: 17,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_1,
            status: "booked",
          },
          {
            id: 93,
            rowNumber: 1,
            seatNumber: 18,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_1,
            status: "booked",
          },
          {
            id: 94,
            rowNumber: 1,
            seatNumber: 19,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_1,
            status: "booked",
          },
          {
            id: 95,
            rowNumber: 1,
            seatNumber: 20,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_1,
            status: "booked",
          },
        ],
        "2": [
          null,
          null,
          null,
          {
            id: 96,
            rowNumber: 2,
            seatNumber: 9,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_2,
            status: "booked",
          },
          {
            id: 97,
            rowNumber: 2,
            seatNumber: 10,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_2,
            status: "booked",
          },
          {
            id: 98,
            rowNumber: 2,
            seatNumber: 11,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_2,
            status: "booked",
          },
          {
            id: 99,
            rowNumber: 2,
            seatNumber: 12,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_2,
            status: "booked",
          },
          {
            id: 100,
            rowNumber: 2,
            seatNumber: 13,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_2,
            status: "booked",
          },
          {
            id: 101,
            rowNumber: 2,
            seatNumber: 14,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_2,
            status: "booked",
          },
          {
            id: 102,
            rowNumber: 2,
            seatNumber: 15,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_2,
            status: "booked",
          },
          {
            id: 103,
            rowNumber: 2,
            seatNumber: 16,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_2,
            status: "booked",
          },
        ],
        "3": [
          null,
          null,
          null,
          {
            id: 104,
            rowNumber: 3,
            seatNumber: 9,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_3,
            status: "booked",
          },
          {
            id: 105,
            rowNumber: 3,
            seatNumber: 10,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_3,
            status: "booked",
          },
          {
            id: 106,
            rowNumber: 3,
            seatNumber: 11,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_3,
            status: "booked",
          },
          {
            id: 107,
            rowNumber: 3,
            seatNumber: 12,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_3,
            status: "booked",
          },
          {
            id: 108,
            rowNumber: 3,
            seatNumber: 13,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_3,
            status: "booked",
          },
          {
            id: 109,
            rowNumber: 3,
            seatNumber: 14,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_3,
            status: "booked",
          },
          {
            id: 110,
            rowNumber: 3,
            seatNumber: 15,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_3,
            status: "booked",
          },
          {
            id: 111,
            rowNumber: 3,
            seatNumber: 16,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_3,
            status: "booked",
          },
        ],
        "4": [
          null,
          null,
          null,
          {
            id: 112,
            rowNumber: 4,
            seatNumber: 9,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_4,
            status: "booked",
          },
          {
            id: 113,
            rowNumber: 4,
            seatNumber: 10,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_4,
            status: "booked",
          },
          {
            id: 114,
            rowNumber: 4,
            seatNumber: 11,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_4,
            status: "booked",
          },
          {
            id: 115,
            rowNumber: 4,
            seatNumber: 12,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_4,
            status: "booked",
          },
          {
            id: 116,
            rowNumber: 4,
            seatNumber: 13,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_4,
            status: "booked",
          },
          {
            id: 117,
            rowNumber: 4,
            seatNumber: 14,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_4,
            status: "booked",
          },
          {
            id: 118,
            rowNumber: 4,
            seatNumber: 15,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_4,
            status: "booked",
          },
          {
            id: 119,
            rowNumber: 4,
            seatNumber: 16,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_4,
            status: "booked",
          },
        ],
        "5": null,
        "6": null,
        "7": null,
        "8": [
          {
            id: 120,
            rowNumber: 8,
            seatNumber: 9,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_8,
            status: "booked",
          },
          {
            id: 121,
            rowNumber: 8,
            seatNumber: 10,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_8,
            status: "booked",
          },
          {
            id: 122,
            rowNumber: 8,
            seatNumber: 11,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_8,
            status: "booked",
          },
          {
            id: 123,
            rowNumber: 8,
            seatNumber: 12,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_8,
            status: "free",
          },
          {
            id: 124,
            rowNumber: 8,
            seatNumber: 13,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_8,
            status: "free",
          },
          {
            id: 125,
            rowNumber: 8,
            seatNumber: 14,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_8,
            status: "free",
          },
          {
            id: 126,
            rowNumber: 8,
            seatNumber: 15,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_8,
            status: "free",
          },
          {
            id: 127,
            rowNumber: 8,
            seatNumber: 16,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_8,
            status: "booked",
          },
          {
            id: 128,
            rowNumber: 8,
            seatNumber: 17,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_8,
            status: "booked",
          },
          {
            id: 129,
            rowNumber: 8,
            seatNumber: 18,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_8,
            status: "booked",
          },
          {
            id: 130,
            rowNumber: 8,
            seatNumber: 19,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_8,
            status: "booked",
          },
          {
            id: 131,
            rowNumber: 8,
            seatNumber: 20,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_8,
            status: "free",
          },
          {
            id: 132,
            rowNumber: 8,
            seatNumber: 21,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_8,
            status: "free",
          },
          {
            id: 133,
            rowNumber: 8,
            seatNumber: 22,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_8,
            status: "free",
          },
        ],
        "9": [
          {
            id: 134,
            rowNumber: 9,
            seatNumber: 9,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_9,
            status: "free",
          },
          {
            id: 135,
            rowNumber: 9,
            seatNumber: 10,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_9,
            status: "free",
          },
          {
            id: 136,
            rowNumber: 9,
            seatNumber: 11,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_9,
            status: "free",
          },
          {
            id: 137,
            rowNumber: 9,
            seatNumber: 12,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_9,
            status: "free",
          },
          {
            id: 138,
            rowNumber: 9,
            seatNumber: 13,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_9,
            status: "booked",
          },
          {
            id: 139,
            rowNumber: 9,
            seatNumber: 14,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_9,
            status: "booked",
          },
          {
            id: 140,
            rowNumber: 9,
            seatNumber: 15,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_9,
            status: "booked",
          },
          {
            id: 141,
            rowNumber: 9,
            seatNumber: 16,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_9,
            status: "free",
          },
          {
            id: 142,
            rowNumber: 9,
            seatNumber: 17,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_9,
            status: "free",
          },
          {
            id: 143,
            rowNumber: 9,
            seatNumber: 18,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_9,
            status: "free",
          },
          {
            id: 144,
            rowNumber: 9,
            seatNumber: 19,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_9,
            status: "free",
          },
          {
            id: 145,
            rowNumber: 9,
            seatNumber: 20,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_9,
            status: "pending",
          },
          {
            id: 146,
            rowNumber: 9,
            seatNumber: 21,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_9,
            status: "pending",
          },
          {
            id: 147,
            rowNumber: 9,
            seatNumber: 22,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_9,
            status: "pending",
          },
        ],
        "10": [
          {
            id: 148,
            rowNumber: 10,
            seatNumber: 9,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_10,
            status: "free",
          },
          {
            id: 149,
            rowNumber: 10,
            seatNumber: 10,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_10,
            status: "free",
          },
          {
            id: 150,
            rowNumber: 10,
            seatNumber: 11,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_10,
            status: "free",
          },
          {
            id: 151,
            rowNumber: 10,
            seatNumber: 12,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_10,
            status: "free",
          },
          {
            id: 152,
            rowNumber: 10,
            seatNumber: 13,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_10,
            status: "free",
          },
          {
            id: 153,
            rowNumber: 10,
            seatNumber: 14,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_10,
            status: "free",
          },
          {
            id: 154,
            rowNumber: 10,
            seatNumber: 15,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_10,
            status: "booked",
          },
          {
            id: 155,
            rowNumber: 10,
            seatNumber: 16,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_10,
            status: "booked",
          },
          {
            id: 156,
            rowNumber: 10,
            seatNumber: 17,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_10,
            status: "booked",
          },
          {
            id: 157,
            rowNumber: 10,
            seatNumber: 18,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_10,
            status: "free",
          },
          {
            id: 158,
            rowNumber: 10,
            seatNumber: 19,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_10,
            status: "free",
          },
          {
            id: 159,
            rowNumber: 10,
            seatNumber: 20,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_10,
            status: "free",
          },
          {
            id: 160,
            rowNumber: 10,
            seatNumber: 21,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_10,
            status: "free",
          },
          {
            id: 161,
            rowNumber: 10,
            seatNumber: 22,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_10,
            status: "free",
          },
        ],
      },
    },
    {
      id: 3,
      seatByRow: {
        "1": [
          null,
          null,
          null,
          null,
          {
            id: 163,
            rowNumber: 1,
            seatNumber: 21,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_1,
            status: "booked",
          },
          {
            id: 164,
            rowNumber: 1,
            seatNumber: 22,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_1,
            status: "booked",
          },
          {
            id: 165,
            rowNumber: 1,
            seatNumber: 23,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_1,
            status: "booked",
          },
          {
            id: 166,
            rowNumber: 1,
            seatNumber: 24,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_1,
            status: "booked",
          },
          {
            id: 167,
            rowNumber: 1,
            seatNumber: 25,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_1,
            status: "booked",
          },
          {
            id: 168,
            rowNumber: 1,
            seatNumber: 26,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_1,
            status: "booked",
          },
          {
            id: 169,
            rowNumber: 1,
            seatNumber: 27,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_1,
            status: "booked",
          },
          {
            id: 170,
            rowNumber: 1,
            seatNumber: 28,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_1,
            status: "booked",
          },
        ],
        "2": [
          null,
          null,
          null,
          null,
          null,
          null,
          {
            id: 171,
            rowNumber: 2,
            seatNumber: 17,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_2,
            status: "booked",
          },
          {
            id: 172,
            rowNumber: 2,
            seatNumber: 18,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_2,
            status: "booked",
          },
          {
            id: 173,
            rowNumber: 2,
            seatNumber: 19,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_2,
            status: "booked",
          },
          {
            id: 174,
            rowNumber: 2,
            seatNumber: 20,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_2,
            status: "booked",
          },
          {
            id: 175,
            rowNumber: 2,
            seatNumber: 21,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_2,
            status: "booked",
          },
          {
            id: 176,
            rowNumber: 2,
            seatNumber: 22,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_2,
            status: "booked",
          },
          {
            id: 177,
            rowNumber: 2,
            seatNumber: 23,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_2,
            status: "booked",
          },
          {
            id: 178,
            rowNumber: 2,
            seatNumber: 24,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_2,
            status: "booked",
          },
        ],
        "3": [
          null,
          null,
          null,
          null,
          null,
          null,
          {
            id: 179,
            rowNumber: 3,
            seatNumber: 17,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_3,
            status: "free",
          },
          {
            id: 180,
            rowNumber: 3,
            seatNumber: 18,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_3,
            status: "free",
          },
          {
            id: 181,
            rowNumber: 3,
            seatNumber: 19,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_3,
            status: "free",
          },
          {
            id: 182,
            rowNumber: 3,
            seatNumber: 20,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_3,
            status: "free",
          },
          {
            id: 183,
            rowNumber: 3,
            seatNumber: 21,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_3,
            status: "free",
          },
          {
            id: 184,
            rowNumber: 3,
            seatNumber: 22,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_3,
            status: "free",
          },
          {
            id: 185,
            rowNumber: 3,
            seatNumber: 23,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_3,
            status: "pending",
          },
          {
            id: 186,
            rowNumber: 3,
            seatNumber: 24,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_3,
            status: "pending",
          },
        ],
        "4": [
          null,
          null,
          null,
          null,
          null,
          null,
          {
            id: 187,
            rowNumber: 4,
            seatNumber: 17,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_4,
            status: "booked",
          },
          {
            id: 188,
            rowNumber: 4,
            seatNumber: 18,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_4,
            status: "booked",
          },
          {
            id: 189,
            rowNumber: 4,
            seatNumber: 19,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_4,
            status: "booked",
          },
          {
            id: 190,
            rowNumber: 4,
            seatNumber: 20,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_4,
            status: "free",
          },
          {
            id: 191,
            rowNumber: 4,
            seatNumber: 21,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_4,
            status: "free",
          },
          {
            id: 192,
            rowNumber: 4,
            seatNumber: 22,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_4,
            status: "booked",
          },
          {
            id: 193,
            rowNumber: 4,
            seatNumber: 23,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_4,
            status: "booked",
          },
          {
            id: 194,
            rowNumber: 4,
            seatNumber: 24,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_4,
            status: "booked",
          },
        ],
        "5": [
          null,
          null,
          null,
          null,
          null,
          null,
          {
            id: 195,
            rowNumber: 5,
            seatNumber: 17,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_5,
            status: "free",
          },
          {
            id: 196,
            rowNumber: 5,
            seatNumber: 18,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_5,
            status: "free",
          },
          {
            id: 197,
            rowNumber: 5,
            seatNumber: 19,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_5,
            status: "free",
          },
          {
            id: 198,
            rowNumber: 5,
            seatNumber: 20,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_5,
            status: "free",
          },
          {
            id: 199,
            rowNumber: 5,
            seatNumber: 21,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_5,
            status: "booked",
          },
          {
            id: 200,
            rowNumber: 5,
            seatNumber: 22,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_5,
            status: "booked",
          },
          {
            id: 201,
            rowNumber: 5,
            seatNumber: 23,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_5,
            status: "booked",
          },
          {
            id: 202,
            rowNumber: 5,
            seatNumber: 24,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_5,
            status: "booked",
          },
        ],
        "6": [
          null,
          null,
          null,
          null,
          null,
          null,
          {
            id: 203,
            rowNumber: 6,
            seatNumber: 17,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_6,
            status: "free",
          },
          {
            id: 204,
            rowNumber: 6,
            seatNumber: 18,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_6,
            status: "booked",
          },
          {
            id: 205,
            rowNumber: 6,
            seatNumber: 19,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_6,
            status: "booked",
          },
          {
            id: 206,
            rowNumber: 6,
            seatNumber: 20,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_6,
            status: "booked",
          },
          {
            id: 207,
            rowNumber: 6,
            seatNumber: 21,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_6,
            status: "free",
          },
          {
            id: 208,
            rowNumber: 6,
            seatNumber: 22,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_6,
            status: "free",
          },
          {
            id: 209,
            rowNumber: 6,
            seatNumber: 23,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_6,
            status: "free",
          },
          {
            id: 210,
            rowNumber: 6,
            seatNumber: 24,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_6,
            status: "free",
          },
        ],
        "7": [
          null,
          null,
          null,
          null,
          null,
          null,
          {
            id: 211,
            rowNumber: 7,
            seatNumber: 17,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_7,
            status: "booked",
          },
          {
            id: 212,
            rowNumber: 7,
            seatNumber: 18,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_7,
            status: "booked",
          },
          {
            id: 213,
            rowNumber: 7,
            seatNumber: 19,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_7,
            status: "booked",
          },
          {
            id: 214,
            rowNumber: 7,
            seatNumber: 20,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_7,
            status: "booked",
          },
          {
            id: 215,
            rowNumber: 7,
            seatNumber: 21,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_7,
            status: "free",
          },
          {
            id: 216,
            rowNumber: 7,
            seatNumber: 22,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_7,
            status: "free",
          },
          {
            id: 217,
            rowNumber: 7,
            seatNumber: 23,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_7,
            status: "free",
          },
          {
            id: 218,
            rowNumber: 7,
            seatNumber: 24,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_7,
            status: "free",
          },
        ],
        "8": [
          null,
          null,
          null,
          null,
          null,
          null,
          {
            id: 219,
            rowNumber: 8,
            seatNumber: 23,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_8,
            status: "free",
          },
          {
            id: 220,
            rowNumber: 8,
            seatNumber: 24,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_8,
            status: "free",
          },
          {
            id: 221,
            rowNumber: 8,
            seatNumber: 25,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_8,
            status: "free",
          },
          {
            id: 222,
            rowNumber: 8,
            seatNumber: 26,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_8,
            status: "free",
          },
          {
            id: 223,
            rowNumber: 8,
            seatNumber: 27,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_8,
            status: "free",
          },
          {
            id: 224,
            rowNumber: 8,
            seatNumber: 28,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_8,
            status: "free",
          },
          {
            id: 225,
            rowNumber: 8,
            seatNumber: 29,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_8,
            status: "free",
          },
          {
            id: 226,
            rowNumber: 8,
            seatNumber: 30,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_8,
            status: "free",
          },
        ],
        "9": [
          null,
          null,
          null,
          null,
          null,
          null,
          {
            id: 227,
            rowNumber: 9,
            seatNumber: 23,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_9,
            status: "free",
          },
          {
            id: 228,
            rowNumber: 9,
            seatNumber: 24,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_9,
            status: "free",
          },
          {
            id: 229,
            rowNumber: 9,
            seatNumber: 25,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_9,
            status: "free",
          },
          {
            id: 230,
            rowNumber: 9,
            seatNumber: 26,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_9,
            status: "free",
          },
          {
            id: 231,
            rowNumber: 9,
            seatNumber: 27,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_9,
            status: "free",
          },
          {
            id: 232,
            rowNumber: 9,
            seatNumber: 28,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_9,
            status: "free",
          },
          {
            id: 233,
            rowNumber: 9,
            seatNumber: 29,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_9,
            status: "free",
          },
          {
            id: 234,
            rowNumber: 9,
            seatNumber: 30,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_9,
            status: "free",
          },
        ],
        "10": [
          null,
          null,
          null,
          null,
          null,
          null,
          {
            id: 235,
            rowNumber: 10,
            seatNumber: 23,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_10,
            status: "nonSale",
          },
          {
            id: 236,
            rowNumber: 10,
            seatNumber: 24,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_10,
            status: "nonSale",
          },
          {
            id: 237,
            rowNumber: 10,
            seatNumber: 25,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_10,
            status: "nonSale",
          },
          {
            id: 238,
            rowNumber: 10,
            seatNumber: 26,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_10,
            status: "nonSale",
          },
          {
            id: 239,
            rowNumber: 10,
            seatNumber: 27,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_10,
            status: "nonSale",
          },
          {
            id: 240,
            rowNumber: 10,
            seatNumber: 28,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_10,
            status: "nonSale",
          },
          {
            id: 241,
            rowNumber: 10,
            seatNumber: 29,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_10,
            status: "nonSale",
          },
          {
            id: 242,
            rowNumber: 10,
            seatNumber: 30,
            seatPrice: WEST_MALL_Prices.PRICE_ROW_10,
            status: "nonSale",
          },
        ],
      },
    },
  ],
};
