import { Showing } from "@/lib/data.type";

export const showingsData: Showing[] = [
  {
    activityData: {
      id: 1111,
      title: "کنسرت یک خواننده معروف",
      location: "سالن میلاد نمایشگاه بین المللی",
      hallId: "111",
      city: "تهران",
      date: "جمعه 28 دی",
      time: "21:30",
    },
    id: 2222,
    remainingTickets: 20,
    date: "جمعه 28 دی",
    time: "21:30",
  },
  {
    activityData: {
      id: 1112,
      title: "نمایش یک روز خاموش",
      location: "پردیس تئاتر شهرزاد",
      hallId: "112",
      city: "تهران",
      date: "پنج‌شنبه 1 بهمن",
      time: "21:00",
    },
    id: 2224,
    remainingTickets: 10,
    date: "پنج‌شنبه 1 بهمن",
    time: "21:00",
  },
  {
    activityData: {
      id: 1112,
      title: "نمایش یک روز خاموش",
      location: "پردیس تئاتر شهرزاد",
      hallId: "112",
      city: "تهران",
      date: "جمعه 2 بهمن",
      time: "18:00",
    },
    id: 2225,
    remainingTickets: 200,
    date: "جمعه 2 بهمن",
    time: "18:00",
  },
  {
    activityData: {
      id: 1112,
      title: "نمایش یک روز خاموش",
      location: "پردیس تئاتر شهرزاد",
      hallId: "112",
      city: "تهران",
      date: "پنج‌شنبه 1 تا 3 بهمن",
      time: "18:00",
    },
    id: 2226,
    remainingTickets: 44,
    date: "شنبه 3 بهمن",
    time: "18:00",
  },
  {
    activityData: {
      id: 1114,
      title: "نامه ای به خود",
      location: "سالن میلاد نمایشگاه بین المللی",
      hallId: "111",
      city: "تهران",
      date: "سه‌شنبه 25 دی",
      time: "21:00",
    },
    id: 2228,
    remainingTickets: 64,
    date: "سه‌شنبه 25 دی",
    time: "21:00",
  },
  {
    activityData: {
      id: 1115,
      title: "کنسرت گروه جدید بند",
      location: "تالار مرکزی",
      hallId: "114",
      city: "شیراز",
      date: "سه‌شنبه 25 تا 28 دی",
      time: "21:30",
    },
    id: 2229,
    remainingTickets: 19,
    date: "سه‌شنبه 25 دی",
    time: "21:30",
  },
  {
    activityData: {
      id: 1115,
      title: "کنسرت گروه جدید بند",
      location: "تالار مرکزی",
      hallId: "114",
      city: "شیراز",
      date: "سه‌شنبه 25 تا 28 دی",
      time: "21:30",
    },
    id: 2230,
    remainingTickets: 19,
    date: "چهارشنبه 26 دی",
    time: "21:30",
  },
  {
    activityData: {
      id: 1115,
      title: "کنسرت گروه جدید بند",
      location: "تالار مرکزی",
      hallId: "114",
      city: "شیراز",
      date: "سه‌شنبه 25 تا 28 دی",
      time: "21:30",
    },
    id: 2231,
    remainingTickets: 20,
    date: "پنج‌شنبه 27 دی",
    time: "21:30",
  },
  {
    activityData: {
      id: 1115,
      title: "کنسرت گروه جدید بند",
      location: "تالار مرکزی",
      hallId: "114",
      city: "شیراز",
      date: "سه‌شنبه 25 تا 28 دی",
      time: "21:30",
    },
    id: 2232,
    remainingTickets: 5,
    date: "جمعه 28 دی",
    time: "21:30",
  },
  {
    activityData: {
      id: 1116,
      title: "کنسرت گروه ارکستر صدای زندگی",
      location: "سالن اجرای موسیقی",
      hallId: "115",
      city: "کرج",
      date: "شنبه 22 تا 23 دی",
      time: "19:00",
    },
    id: 2235,
    remainingTickets: 2,
    date: "شنبه 22 دی",
    time: "19:00",
  },
  {
    activityData: {
      id: 1116,
      title: "کنسرت گروه ارکستر صدای زندگی",
      location: "سالن اجرای موسیقی",
      hallId: "115",
      city: "کرج",
      date: "شنبه 22 تا 23 دی",
      time: "19:00",
    },
    id: 2236,
    remainingTickets: 35,
    date: "یک‌شنبه 23 دی",
    time: "19:00",
  },
  {
    activityData: {
      id: 1117,
      title: "من بی تو - نمایشنامه خوانی",
      location: "سالن تئاتر شهر",
      hallId: "116",
      city: "اصفهان",
      date: "شنبه 29 دی",
      time: "20:30",
    },
    id: 2237,
    remainingTickets: 72,
    date: "شنبه 29 دی",
    time: "20:30",
  },
  {
    activityData: {
      id: 1118,
      title: "کنسرت خواننده معروف",
      location: "سالن موسیقی مرکزی",
      hallId: "117",
      city: "اصفهان",
      date: "سه‌شنبه 25 دی",
      time: "18:30",
    },
    id: 2241,
    remainingTickets: 112,
    date: "سه‌شنبه 25 دی",
    time: "18:30",
  },
  {
    activityData: {
      id: 1119,
      title: "دوئت گیتار گروه راک بند",
      location: "پردیس تئاتر شهرزاد",
      hallId: "112",
      city: "تهران",
      date: "سه‌شنبه 25 دی",
      time: "18:00",
    },
    id: 2243,
    remainingTickets: 13,
    date: "سه‌شنبه 25 دی",
    time: "18:00",
  },
  {
    activityData: {
      id: 1120,
      title: "کنسرت خواننده محبوب",
      location: "تالار اصلی شهر",
      hallId: "118",
      city: "رشت",
      date: "پنج‌شنبه 27 دی",
      time: "20:00",
    },
    id: 2244,
    remainingTickets: 98,
    date: "پنج‌شنبه 27 دی",
    time: "20:00",
  },
  {
    activityData: {
      id: 1124,
      title: "پاریس من (نمایش فرنگی)",
      location: "سالن شهرداری",
      hallId: "119",
      city: "گرگان",
      date: "سه‌شنبه 2 تا 4 بهمن",
      time: "20:00",
    },
    id: 2250,
    remainingTickets: 120,
    date: "سه‌شنبه 2 بهمن",
    time: "20:00",
  },
  {
    activityData: {
      id: 1124,
      title: "پاریس من (نمایش فرنگی)",
      location: "سالن شهرداری",
      hallId: "119",
      city: "گرگان",
      date: "سه‌شنبه 2 تا 4 بهمن",
      time: "20:00",
    },
    id: 2251,
    remainingTickets: 150,
    date: "چهارشنبه 3 بهمن",
    time: "20:00",
  },
  {
    activityData: {
      id: 1124,
      title: "پاریس من (نمایش فرنگی)",
      location: "سالن شهرداری",
      hallId: "119",
      city: "گرگان",
      date: "سه‌شنبه 2 تا 4 بهمن",
      time: "20:00",
    },
    id: 2252,
    remainingTickets: 200,
    date: "پنج‌شنبه 4 بهمن",
    time: "20:00",
  },
  {
    activityData: {
      id: 1125,
      title: "اپرای زنان کوچک",
      location: "سالن موسیقی مرکزی",
      hallId: "117",
      city: "تبریز",
      date: "پنج‌شنبه 4 بهمن",
      time: "18:30",
    },
    id: 2253,
    remainingTickets: 234,
    date: "پنج‌شنبه 4 بهمن",
    time: "18:30",
  },
  {
    activityData: {
      id: 1125,
      title: "اپرای زنان کوچک",
      location: "سالن موسیقی مرکزی",
      hallId: "117",
      city: "تبریز",
      date: "جمعه 5 بهمن",
      time: "18:30",
    },
    id: 2254,
    remainingTickets: 176,
    date: "جمعه 5 بهمن",
    time: "18:30",
  },
  {
    activityData: {
      id: 1126,
      title: "کنسرت تازه بند",
      location: "سالن مال غربی",
      hallId: "120",
      city: "تهران",
      date: "سه‌شنبه 25 دی",
      time: "21:30",
    },
    id: 2255,
    remainingTickets: 102,
    date: "سه‌شنبه 25 دی",
    time: "21:30",
  },
  {
    activityData: {
      id: 1128,
      title: "تئاتر موزیکال شکسپیر",
      location: "تالار بزرگ شهر",
      hallId: "121",
      city: "قزوین",
      date: "شنبه 1 بهمن",
      time: "20:00",
    },
    id: 2257,
    remainingTickets: 67,
    date: "شنبه 1 بهمن",
    time: "20:00",
  },
];
