import { Hall } from "@/lib/hall-data/hall.type";

import { RowPrices } from "@/lib/hall-data/halls-prices.type";

import {
  MAX_MOBILE_WIDTH,
  MIN_DESKTOP_WIDTH,
} from "@/app/activity/[id]/constants/canvas.constants";

export const WEST_MALL_PRICES: RowPrices = {
  PRICE_ROW_1: {
    label: "ردیف 1",
    value: 1100000,
  },
  PRICE_ROW_2: {
    label: "ردیف 2",
    value: 1100000,
  },
  PRICE_ROW_3: {
    label: "ردیف 3",
    value: 1100000,
  },
  PRICE_ROW_4: {
    label: "ردیف 4",
    value: 1100000,
  },
  PRICE_ROW_5: {
    label: "ردیف 5",
    value: 850000,
  },
  PRICE_ROW_6: {
    label: "ردیف 6",
    value: 850000,
  },
  PRICE_ROW_7: {
    label: "ردیف 7",
    value: 850000,
  },
  PRICE_ROW_8: {
    label: "ردیف 8",
    value: 800000,
  },
  PRICE_ROW_9: {
    label: "ردیف 9",
    value: 800000,
  },
  PRICE_ROW_10: {
    label: "ردیف 10",
    value: 800000,
  },
  PRICE_ROW_11: {
    label: "ردیف 11",
    value: 800000,
  },
  PRICE_ROW_12: {
    label: "ردیف 12",
    value: 600000,
  },
  PRICE_ROW_13: {
    label: "ردیف 13",
    value: 600000,
  },
  PRICE_ROW_14: {
    label: "ردیف 14",
    value: 400000,
  },
  PRICE_ROW_15: {
    label: "ردیف 15",
    value: 400000,
  },
};

export const WEST_MALL: Hall = {
  id: "120",
  name: "سالن مال غربی",
  capacity: 490,
  city: "تهران",
  getCanvasMidPoint: (canvasWidth) => {
    let divideNumber;

    if (canvasWidth >= MIN_DESKTOP_WIDTH) {
      divideNumber = 2.9;
    } else if (canvasWidth >= MAX_MOBILE_WIDTH) {
      divideNumber = 2.95;
    } else {
      divideNumber = 2.85;
    }

    return canvasWidth / divideNumber;
  },
  getRowsOffsetX: (seatWidth, desktopRectMargin) => {
    return {
      0: 3 * seatWidth + 3 * desktopRectMargin,
      1: 2 * seatWidth + 2 * desktopRectMargin,
      2: seatWidth + desktopRectMargin,
      3: 0,
      4: -seatWidth - desktopRectMargin,
      5: 0,
      6: 0,
      7: 2 * seatWidth + 2 * desktopRectMargin,
      8: 2 * seatWidth + 2 * desktopRectMargin,
      9: seatWidth + desktopRectMargin,
      10: 0,
      11: -seatWidth - desktopRectMargin,
      12: seatWidth + desktopRectMargin,
      13: 4 * seatWidth + 4 * desktopRectMargin,
      14: 4 * seatWidth + 4 * desktopRectMargin,
      15: 4 * seatWidth + 4 * desktopRectMargin,
    };
  },
  getRowsOffsetY: (seatWidth, desktopRectMargin) => {
    return {
      0: 0,
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
      6: 0,
      7: 0,
      8: 0,
      9: 0,
      10: 0,
      11: 0,
      12: 0,
      13: -seatWidth - desktopRectMargin,
      14: -seatWidth - desktopRectMargin,
      15: -seatWidth - desktopRectMargin,
    };
  },
  seatsByRow: [
    /* row 1 */
    [
      {
        id: 1111,
        rowNumber: 1,
        seatNumber: 1,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_1.value,
        status: "free",
      },
      {
        id: 1112,
        rowNumber: 1,
        seatNumber: 2,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_1.value,
        status: "free",
      },
      {
        id: 1113,
        rowNumber: 1,
        seatNumber: 3,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_1.value,
        status: "booked",
      },
      {
        id: 1114,
        rowNumber: 1,
        seatNumber: 4,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_1.value,
        status: "booked",
      },
      {
        id: 1115,
        rowNumber: 1,
        seatNumber: 5,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_1.value,
        status: "booked",
      },
      {
        id: 1116,
        rowNumber: 1,
        seatNumber: 6,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_1.value,
        status: "booked",
      },
      {
        id: 1117,
        rowNumber: 1,
        seatNumber: 7,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_1.value,
        status: "booked",
      },
      {
        id: 1118,
        rowNumber: 1,
        seatNumber: 8,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_1.value,
        status: "booked",
      },
      null,
      null,
      {
        id: 1119,
        rowNumber: 1,
        seatNumber: 9,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_1.value,
        status: "booked",
      },
      {
        id: 1120,
        rowNumber: 1,
        seatNumber: 10,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_1.value,
        status: "booked",
      },
      {
        id: 1121,
        rowNumber: 1,
        seatNumber: 11,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_1.value,
        status: "booked",
      },
      {
        id: 1122,
        rowNumber: 1,
        seatNumber: 12,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_1.value,
        status: "booked",
      },
      {
        id: 1123,
        rowNumber: 1,
        seatNumber: 13,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_1.value,
        status: "booked",
      },
      {
        id: 1124,
        rowNumber: 1,
        seatNumber: 14,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_1.value,
        status: "booked",
      },
      {
        id: 1125,
        rowNumber: 1,
        seatNumber: 15,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_1.value,
        status: "booked",
      },
      {
        id: 1126,
        rowNumber: 1,
        seatNumber: 16,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_1.value,
        status: "booked",
      },
      {
        id: 1127,
        rowNumber: 1,
        seatNumber: 17,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_1.value,
        status: "booked",
      },
      {
        id: 1128,
        rowNumber: 1,
        seatNumber: 18,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_1.value,
        status: "booked",
      },
      {
        id: 1129,
        rowNumber: 1,
        seatNumber: 19,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_1.value,
        status: "booked",
      },
      {
        id: 1130,
        rowNumber: 1,
        seatNumber: 20,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_1.value,
        status: "booked",
      },
      null,
      null,
      {
        id: 1131,
        rowNumber: 1,
        seatNumber: 21,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_1.value,
        status: "booked",
      },
      {
        id: 1132,
        rowNumber: 1,
        seatNumber: 22,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_1.value,
        status: "booked",
      },
      {
        id: 1133,
        rowNumber: 1,
        seatNumber: 23,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_1.value,
        status: "free",
      },
      {
        id: 1134,
        rowNumber: 1,
        seatNumber: 24,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_1.value,
        status: "free",
      },
      {
        id: 1135,
        rowNumber: 1,
        seatNumber: 25,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_1.value,
        status: "free",
      },
      {
        id: 1136,
        rowNumber: 1,
        seatNumber: 26,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_1.value,
        status: "booked",
      },
      {
        id: 1137,
        rowNumber: 1,
        seatNumber: 27,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_1.value,
        status: "booked",
      },
      {
        id: 1138,
        rowNumber: 1,
        seatNumber: 28,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_1.value,
        status: "booked",
      },
    ],

    /* row 2 */
    [
      {
        id: 1139,
        rowNumber: 2,
        seatNumber: 1,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_2.value,
        status: "booked",
      },
      {
        id: 1140,
        rowNumber: 2,
        seatNumber: 2,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_2.value,
        status: "booked",
      },
      {
        id: 1141,
        rowNumber: 2,
        seatNumber: 3,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_2.value,
        status: "booked",
      },
      {
        id: 1142,
        rowNumber: 2,
        seatNumber: 4,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_2.value,
        status: "booked",
      },
      {
        id: 1143,
        rowNumber: 2,
        seatNumber: 5,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_2.value,
        status: "booked",
      },
      {
        id: 1144,
        rowNumber: 2,
        seatNumber: 6,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_2.value,
        status: "booked",
      },
      {
        id: 1145,
        rowNumber: 2,
        seatNumber: 7,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_2.value,
        status: "booked",
      },
      {
        id: 1146,
        rowNumber: 2,
        seatNumber: 8,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_2.value,
        status: "booked",
      },
      null,
      null,
      {
        id: 1147,
        rowNumber: 2,
        seatNumber: 9,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_2.value,
        status: "booked",
      },
      {
        id: 1148,
        rowNumber: 2,
        seatNumber: 10,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_2.value,
        status: "booked",
      },
      {
        id: 1149,
        rowNumber: 2,
        seatNumber: 11,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_2.value,
        status: "booked",
      },
      {
        id: 1150,
        rowNumber: 2,
        seatNumber: 12,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_2.value,
        status: "booked",
      },
      {
        id: 1151,
        rowNumber: 2,
        seatNumber: 13,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_2.value,
        status: "booked",
      },
      {
        id: 1152,
        rowNumber: 2,
        seatNumber: 14,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_2.value,
        status: "booked",
      },
      {
        id: 1153,
        rowNumber: 2,
        seatNumber: 15,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_2.value,
        status: "booked",
      },
      {
        id: 1154,
        rowNumber: 2,
        seatNumber: 16,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_2.value,
        status: "booked",
      },
      {
        id: 1155,
        rowNumber: 2,
        seatNumber: 17,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_2.value,
        status: "booked",
      },
      {
        id: 1156,
        rowNumber: 2,
        seatNumber: 18,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_2.value,
        status: "booked",
      },
      {
        id: 1157,
        rowNumber: 2,
        seatNumber: 19,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_2.value,
        status: "booked",
      },
      {
        id: 1158,
        rowNumber: 2,
        seatNumber: 20,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_2.value,
        status: "booked",
      },
      {
        id: 1159,
        rowNumber: 2,
        seatNumber: 21,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_2.value,
        status: "booked",
      },
      {
        id: 1160,
        rowNumber: 2,
        seatNumber: 22,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_2.value,
        status: "booked",
      },
      null,
      null,
      {
        id: 1161,
        rowNumber: 2,
        seatNumber: 23,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_2.value,
        status: "booked",
      },
      {
        id: 1162,
        rowNumber: 2,
        seatNumber: 24,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_2.value,
        status: "booked",
      },
      {
        id: 1163,
        rowNumber: 2,
        seatNumber: 25,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_2.value,
        status: "booked",
      },
      {
        id: 1164,
        rowNumber: 2,
        seatNumber: 26,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_2.value,
        status: "booked",
      },
      {
        id: 1165,
        rowNumber: 2,
        seatNumber: 27,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_2.value,
        status: "booked",
      },
      {
        id: 1166,
        rowNumber: 2,
        seatNumber: 28,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_2.value,
        status: "booked",
      },
      {
        id: 1167,
        rowNumber: 2,
        seatNumber: 29,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_2.value,
        status: "booked",
      },
      {
        id: 1168,
        rowNumber: 2,
        seatNumber: 30,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_2.value,
        status: "booked",
      },
    ],

    /* row 3 */
    [
      {
        id: 1169,
        rowNumber: 3,
        seatNumber: 1,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_3.value,
        status: "free",
      },
      {
        id: 1170,
        rowNumber: 3,
        seatNumber: 2,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_3.value,
        status: "free",
      },
      {
        id: 1171,
        rowNumber: 3,
        seatNumber: 3,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_3.value,
        status: "booked",
      },
      {
        id: 1172,
        rowNumber: 3,
        seatNumber: 4,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_3.value,
        status: "booked",
      },
      {
        id: 1173,
        rowNumber: 3,
        seatNumber: 5,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_3.value,
        status: "booked",
      },
      {
        id: 1174,
        rowNumber: 3,
        seatNumber: 6,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_3.value,
        status: "booked",
      },
      {
        id: 1175,
        rowNumber: 3,
        seatNumber: 7,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_3.value,
        status: "booked",
      },
      {
        id: 1176,
        rowNumber: 3,
        seatNumber: 8,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_3.value,
        status: "booked",
      },
      null,
      null,
      {
        id: 1177,
        rowNumber: 3,
        seatNumber: 9,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_3.value,
        status: "booked",
      },
      {
        id: 1178,
        rowNumber: 3,
        seatNumber: 10,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_3.value,
        status: "booked",
      },
      {
        id: 1179,
        rowNumber: 3,
        seatNumber: 11,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_3.value,
        status: "booked",
      },
      {
        id: 1180,
        rowNumber: 3,
        seatNumber: 12,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_3.value,
        status: "booked",
      },
      {
        id: 1181,
        rowNumber: 3,
        seatNumber: 13,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_3.value,
        status: "booked",
      },
      {
        id: 1182,
        rowNumber: 3,
        seatNumber: 14,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_3.value,
        status: "booked",
      },
      {
        id: 1183,
        rowNumber: 3,
        seatNumber: 15,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_3.value,
        status: "booked",
      },
      {
        id: 1184,
        rowNumber: 3,
        seatNumber: 16,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_3.value,
        status: "booked",
      },
      {
        id: 1185,
        rowNumber: 3,
        seatNumber: 17,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_3.value,
        status: "booked",
      },
      {
        id: 1186,
        rowNumber: 3,
        seatNumber: 18,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_3.value,
        status: "booked",
      },
      {
        id: 1187,
        rowNumber: 3,
        seatNumber: 19,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_3.value,
        status: "booked",
      },
      {
        id: 1188,
        rowNumber: 3,
        seatNumber: 20,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_3.value,
        status: "booked",
      },
      {
        id: 1189,
        rowNumber: 3,
        seatNumber: 21,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_3.value,
        status: "booked",
      },
      {
        id: 1190,
        rowNumber: 3,
        seatNumber: 22,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_3.value,
        status: "booked",
      },
      {
        id: 1191,
        rowNumber: 3,
        seatNumber: 23,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_3.value,
        status: "booked",
      },
      {
        id: 1192,
        rowNumber: 3,
        seatNumber: 24,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_3.value,
        status: "booked",
      },
      null,
      null,
      {
        id: 1193,
        rowNumber: 3,
        seatNumber: 25,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_3.value,
        status: "booked",
      },
      {
        id: 1194,
        rowNumber: 3,
        seatNumber: 26,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_3.value,
        status: "booked",
      },
      {
        id: 1195,
        rowNumber: 3,
        seatNumber: 27,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_3.value,
        status: "booked",
      },
      {
        id: 1196,
        rowNumber: 3,
        seatNumber: 28,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_3.value,
        status: "booked",
      },
      {
        id: 1197,
        rowNumber: 3,
        seatNumber: 29,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_3.value,
        status: "booked",
      },
      {
        id: 1198,
        rowNumber: 3,
        seatNumber: 30,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_3.value,
        status: "booked",
      },
      {
        id: 1199,
        rowNumber: 3,
        seatNumber: 31,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_3.value,
        status: "booked",
      },
      {
        id: 1200,
        rowNumber: 3,
        seatNumber: 32,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_3.value,
        status: "booked",
      },
    ],

    /* row 4 */
    [
      {
        id: 1201,
        rowNumber: 4,
        seatNumber: 1,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_4.value,
        status: "free",
      },
      {
        id: 1202,
        rowNumber: 4,
        seatNumber: 2,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_4.value,
        status: "free",
      },
      {
        id: 1203,
        rowNumber: 4,
        seatNumber: 3,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_4.value,
        status: "free",
      },
      {
        id: 1204,
        rowNumber: 4,
        seatNumber: 4,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_4.value,
        status: "free",
      },
      {
        id: 1205,
        rowNumber: 4,
        seatNumber: 5,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_4.value,
        status: "booked",
      },
      {
        id: 1206,
        rowNumber: 4,
        seatNumber: 6,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_4.value,
        status: "booked",
      },
      {
        id: 1207,
        rowNumber: 4,
        seatNumber: 7,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_4.value,
        status: "booked",
      },
      {
        id: 1208,
        rowNumber: 4,
        seatNumber: 8,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_4.value,
        status: "booked",
      },
      null,
      null,
      {
        id: 1209,
        rowNumber: 4,
        seatNumber: 9,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_4.value,
        status: "booked",
      },
      {
        id: 1210,
        rowNumber: 4,
        seatNumber: 10,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_4.value,
        status: "booked",
      },
      {
        id: 1211,
        rowNumber: 4,
        seatNumber: 11,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_4.value,
        status: "booked",
      },
      {
        id: 1212,
        rowNumber: 4,
        seatNumber: 12,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_4.value,
        status: "booked",
      },
      {
        id: 1213,
        rowNumber: 4,
        seatNumber: 13,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_4.value,
        status: "booked",
      },
      {
        id: 1214,
        rowNumber: 4,
        seatNumber: 14,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_4.value,
        status: "booked",
      },
      {
        id: 1215,
        rowNumber: 4,
        seatNumber: 15,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_4.value,
        status: "booked",
      },
      {
        id: 1216,
        rowNumber: 4,
        seatNumber: 16,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_4.value,
        status: "booked",
      },
      {
        id: 1217,
        rowNumber: 4,
        seatNumber: 17,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_4.value,
        status: "booked",
      },
      {
        id: 1218,
        rowNumber: 4,
        seatNumber: 18,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_4.value,
        status: "booked",
      },
      {
        id: 1219,
        rowNumber: 4,
        seatNumber: 19,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_4.value,
        status: "booked",
      },
      {
        id: 1220,
        rowNumber: 4,
        seatNumber: 20,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_4.value,
        status: "booked",
      },
      {
        id: 1221,
        rowNumber: 4,
        seatNumber: 21,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_4.value,
        status: "booked",
      },
      {
        id: 1222,
        rowNumber: 4,
        seatNumber: 22,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_4.value,
        status: "booked",
      },
      {
        id: 1223,
        rowNumber: 4,
        seatNumber: 23,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_4.value,
        status: "booked",
      },
      {
        id: 1224,
        rowNumber: 4,
        seatNumber: 24,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_4.value,
        status: "booked",
      },
      {
        id: 1225,
        rowNumber: 4,
        seatNumber: 25,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_4.value,
        status: "booked",
      },
      {
        id: 1226,
        rowNumber: 4,
        seatNumber: 26,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_4.value,
        status: "booked",
      },
      null,
      null,
      {
        id: 1227,
        rowNumber: 4,
        seatNumber: 27,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_4.value,
        status: "pending",
      },
      {
        id: 1228,
        rowNumber: 4,
        seatNumber: 28,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_4.value,
        status: "pending",
      },
      {
        id: 1229,
        rowNumber: 4,
        seatNumber: 29,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_4.value,
        status: "booked",
      },
      {
        id: 1230,
        rowNumber: 4,
        seatNumber: 30,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_4.value,
        status: "booked",
      },
      {
        id: 1231,
        rowNumber: 4,
        seatNumber: 31,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_4.value,
        status: "booked",
      },
      {
        id: 1232,
        rowNumber: 4,
        seatNumber: 32,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_4.value,
        status: "booked",
      },
      {
        id: 1233,
        rowNumber: 4,
        seatNumber: 33,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_4.value,
        status: "free",
      },
      {
        id: 1234,
        rowNumber: 4,
        seatNumber: 34,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_4.value,
        status: "free",
      },
    ],

    /* row 5 */
    [
      {
        id: 1235,
        rowNumber: 5,
        seatNumber: 1,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_5.value,
        status: "free",
      },
      {
        id: 1236,
        rowNumber: 5,
        seatNumber: 2,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_5.value,
        status: "free",
      },
      {
        id: 1237,
        rowNumber: 5,
        seatNumber: 3,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_5.value,
        status: "free",
      },
      {
        id: 1238,
        rowNumber: 5,
        seatNumber: 4,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_5.value,
        status: "free",
      },
      {
        id: 1239,
        rowNumber: 5,
        seatNumber: 5,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_5.value,
        status: "free",
      },
      {
        id: 1240,
        rowNumber: 5,
        seatNumber: 6,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_5.value,
        status: "free",
      },
      {
        id: 1241,
        rowNumber: 5,
        seatNumber: 7,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_5.value,
        status: "booked",
      },
      {
        id: 1242,
        rowNumber: 5,
        seatNumber: 8,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_5.value,
        status: "booked",
      },
      null,
      null,
      {
        id: 1243,
        rowNumber: 5,
        seatNumber: 9,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_5.value,
        status: "booked",
      },
      {
        id: 1244,
        rowNumber: 5,
        seatNumber: 10,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_5.value,
        status: "booked",
      },
      {
        id: 1245,
        rowNumber: 5,
        seatNumber: 11,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_5.value,
        status: "booked",
      },
      {
        id: 1246,
        rowNumber: 5,
        seatNumber: 12,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_5.value,
        status: "booked",
      },
      {
        id: 1247,
        rowNumber: 5,
        seatNumber: 13,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_5.value,
        status: "booked",
      },
      {
        id: 1248,
        rowNumber: 5,
        seatNumber: 14,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_5.value,
        status: "booked",
      },
      {
        id: 1249,
        rowNumber: 5,
        seatNumber: 15,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_5.value,
        status: "booked",
      },
      {
        id: 1250,
        rowNumber: 5,
        seatNumber: 16,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_5.value,
        status: "booked",
      },
      {
        id: 1251,
        rowNumber: 5,
        seatNumber: 17,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_5.value,
        status: "booked",
      },
      {
        id: 1252,
        rowNumber: 5,
        seatNumber: 18,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_5.value,
        status: "booked",
      },
      {
        id: 1253,
        rowNumber: 5,
        seatNumber: 19,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_5.value,
        status: "booked",
      },
      {
        id: 1254,
        rowNumber: 5,
        seatNumber: 20,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_5.value,
        status: "booked",
      },
      {
        id: 1255,
        rowNumber: 5,
        seatNumber: 21,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_5.value,
        status: "booked",
      },
      {
        id: 1256,
        rowNumber: 5,
        seatNumber: 22,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_5.value,
        status: "booked",
      },
      {
        id: 1257,
        rowNumber: 5,
        seatNumber: 23,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_5.value,
        status: "booked",
      },
      {
        id: 1258,
        rowNumber: 5,
        seatNumber: 24,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_5.value,
        status: "booked",
      },
      {
        id: 1259,
        rowNumber: 5,
        seatNumber: 25,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_5.value,
        status: "booked",
      },
      {
        id: 1260,
        rowNumber: 5,
        seatNumber: 26,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_5.value,
        status: "booked",
      },
      {
        id: 1261,
        rowNumber: 5,
        seatNumber: 27,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_5.value,
        status: "booked",
      },
      {
        id: 1262,
        rowNumber: 5,
        seatNumber: 28,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_5.value,
        status: "booked",
      },
      null,
      null,
      {
        id: 1263,
        rowNumber: 5,
        seatNumber: 29,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_5.value,
        status: "booked",
      },
      {
        id: 1264,
        rowNumber: 5,
        seatNumber: 30,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_5.value,
        status: "free",
      },
      {
        id: 1265,
        rowNumber: 5,
        seatNumber: 31,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_5.value,
        status: "free",
      },
      {
        id: 1266,
        rowNumber: 5,
        seatNumber: 32,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_5.value,
        status: "free",
      },
      {
        id: 1267,
        rowNumber: 5,
        seatNumber: 33,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_5.value,
        status: "booked",
      },
      {
        id: 1268,
        rowNumber: 5,
        seatNumber: 34,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_5.value,
        status: "booked",
      },
      {
        id: 1269,
        rowNumber: 5,
        seatNumber: 35,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_5.value,
        status: "free",
      },
      {
        id: 1270,
        rowNumber: 5,
        seatNumber: 36,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_5.value,
        status: "free",
      },
    ],

    /* row 6 */
    [
      {
        id: 1271,
        rowNumber: 6,
        seatNumber: 1,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_6.value,
        status: "free",
      },
      {
        id: 1272,
        rowNumber: 6,
        seatNumber: 2,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_6.value,
        status: "free",
      },
      {
        id: 1273,
        rowNumber: 6,
        seatNumber: 3,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_6.value,
        status: "free",
      },
      {
        id: 1274,
        rowNumber: 6,
        seatNumber: 4,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_6.value,
        status: "booked",
      },
      {
        id: 1275,
        rowNumber: 6,
        seatNumber: 5,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_6.value,
        status: "booked",
      },
      {
        id: 1276,
        rowNumber: 6,
        seatNumber: 6,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_6.value,
        status: "free",
      },
      {
        id: 1277,
        rowNumber: 6,
        seatNumber: 7,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_6.value,
        status: "free",
      },
      {
        id: 1278,
        rowNumber: 6,
        seatNumber: 8,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_6.value,
        status: "free",
      },
      null,
      {
        id: 1279,
        rowNumber: 6,
        seatNumber: 9,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_6.value,
        status: "free",
      },
      {
        id: 1280,
        rowNumber: 6,
        seatNumber: 10,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_6.value,
        status: "free",
      },
      {
        id: 1281,
        rowNumber: 6,
        seatNumber: 11,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_6.value,
        status: "free",
      },
      {
        id: 1282,
        rowNumber: 6,
        seatNumber: 12,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_6.value,
        status: "free",
      },
      {
        id: 1283,
        rowNumber: 6,
        seatNumber: 13,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_6.value,
        status: "booked",
      },
      {
        id: 1284,
        rowNumber: 6,
        seatNumber: 14,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_6.value,
        status: "booked",
      },
      {
        id: 1285,
        rowNumber: 6,
        seatNumber: 15,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_6.value,
        status: "booked",
      },
      {
        id: 1286,
        rowNumber: 6,
        seatNumber: 16,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_6.value,
        status: "booked",
      },
      {
        id: 1287,
        rowNumber: 6,
        seatNumber: 17,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_6.value,
        status: "booked",
      },
      {
        id: 1288,
        rowNumber: 6,
        seatNumber: 18,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_6.value,
        status: "booked",
      },
      {
        id: 1289,
        rowNumber: 6,
        seatNumber: 19,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_6.value,
        status: "booked",
      },
      {
        id: 1290,
        rowNumber: 6,
        seatNumber: 20,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_6.value,
        status: "booked",
      },
      {
        id: 1291,
        rowNumber: 6,
        seatNumber: 21,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_6.value,
        status: "booked",
      },
      {
        id: 1292,
        rowNumber: 6,
        seatNumber: 22,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_6.value,
        status: "free",
      },
      {
        id: 1293,
        rowNumber: 6,
        seatNumber: 23,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_6.value,
        status: "free",
      },
      {
        id: 1294,
        rowNumber: 6,
        seatNumber: 24,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_6.value,
        status: "free",
      },
      {
        id: 1295,
        rowNumber: 6,
        seatNumber: 25,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_6.value,
        status: "free",
      },
      {
        id: 1296,
        rowNumber: 6,
        seatNumber: 26,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_6.value,
        status: "free",
      },
      {
        id: 1297,
        rowNumber: 6,
        seatNumber: 27,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_6.value,
        status: "booked",
      },
      {
        id: 1298,
        rowNumber: 6,
        seatNumber: 28,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_6.value,
        status: "booked",
      },
      null,
      {
        id: 1299,
        rowNumber: 6,
        seatNumber: 29,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_6.value,
        status: "booked",
      },
      {
        id: 1300,
        rowNumber: 6,
        seatNumber: 30,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_6.value,
        status: "booked",
      },
      {
        id: 1301,
        rowNumber: 6,
        seatNumber: 31,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_6.value,
        status: "booked",
      },
      {
        id: 1302,
        rowNumber: 6,
        seatNumber: 32,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_6.value,
        status: "free",
      },
      {
        id: 1303,
        rowNumber: 6,
        seatNumber: 33,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_6.value,
        status: "free",
      },
      {
        id: 1304,
        rowNumber: 6,
        seatNumber: 34,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_6.value,
        status: "free",
      },
      {
        id: 1305,
        rowNumber: 6,
        seatNumber: 35,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_6.value,
        status: "free",
      },
      {
        id: 1306,
        rowNumber: 6,
        seatNumber: 36,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_6.value,
        status: "free",
      },
    ],

    /* row 7 */
    [
      {
        id: 1307,
        rowNumber: 7,
        seatNumber: 1,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_7.value,
        status: "free",
      },
      {
        id: 1308,
        rowNumber: 7,
        seatNumber: 2,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_7.value,
        status: "free",
      },
      {
        id: 1309,
        rowNumber: 7,
        seatNumber: 3,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_7.value,
        status: "free",
      },
      {
        id: 1310,
        rowNumber: 7,
        seatNumber: 4,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_7.value,
        status: "free",
      },
      {
        id: 1311,
        rowNumber: 7,
        seatNumber: 5,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_7.value,
        status: "free",
      },
      {
        id: 1312,
        rowNumber: 7,
        seatNumber: 6,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_7.value,
        status: "free",
      },
      {
        id: 1313,
        rowNumber: 7,
        seatNumber: 7,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_7.value,
        status: "free",
      },
      {
        id: 1314,
        rowNumber: 7,
        seatNumber: 8,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_7.value,
        status: "free",
      },
      null,
      {
        id: 1315,
        rowNumber: 7,
        seatNumber: 9,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_7.value,
        status: "free",
      },
      {
        id: 1316,
        rowNumber: 7,
        seatNumber: 10,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_7.value,
        status: "free",
      },
      {
        id: 1317,
        rowNumber: 7,
        seatNumber: 11,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_7.value,
        status: "booked",
      },
      {
        id: 1318,
        rowNumber: 7,
        seatNumber: 12,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_7.value,
        status: "booked",
      },
      {
        id: 1319,
        rowNumber: 7,
        seatNumber: 13,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_7.value,
        status: "booked",
      },
      {
        id: 1320,
        rowNumber: 7,
        seatNumber: 14,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_7.value,
        status: "booked",
      },
      {
        id: 1321,
        rowNumber: 7,
        seatNumber: 15,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_7.value,
        status: "free",
      },
      {
        id: 1322,
        rowNumber: 7,
        seatNumber: 16,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_7.value,
        status: "free",
      },
      {
        id: 1323,
        rowNumber: 7,
        seatNumber: 17,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_7.value,
        status: "free",
      },
      {
        id: 1324,
        rowNumber: 7,
        seatNumber: 18,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_7.value,
        status: "free",
      },
      {
        id: 1325,
        rowNumber: 7,
        seatNumber: 19,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_7.value,
        status: "free",
      },
      {
        id: 1326,
        rowNumber: 7,
        seatNumber: 20,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_7.value,
        status: "free",
      },
      {
        id: 1327,
        rowNumber: 7,
        seatNumber: 21,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_7.value,
        status: "free",
      },
      {
        id: 1328,
        rowNumber: 7,
        seatNumber: 22,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_7.value,
        status: "booked",
      },
      {
        id: 1329,
        rowNumber: 7,
        seatNumber: 23,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_7.value,
        status: "booked",
      },
      {
        id: 1330,
        rowNumber: 7,
        seatNumber: 24,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_7.value,
        status: "booked",
      },
      {
        id: 1331,
        rowNumber: 7,
        seatNumber: 25,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_7.value,
        status: "booked",
      },
      {
        id: 1332,
        rowNumber: 7,
        seatNumber: 26,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_7.value,
        status: "booked",
      },
      {
        id: 1333,
        rowNumber: 7,
        seatNumber: 27,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_7.value,
        status: "booked",
      },
      {
        id: 1334,
        rowNumber: 7,
        seatNumber: 28,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_7.value,
        status: "booked",
      },
      null,
      {
        id: 1335,
        rowNumber: 7,
        seatNumber: 29,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_7.value,
        status: "booked",
      },
      {
        id: 1336,
        rowNumber: 7,
        seatNumber: 30,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_7.value,
        status: "booked",
      },
      {
        id: 1337,
        rowNumber: 7,
        seatNumber: 31,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_7.value,
        status: "free",
      },
      {
        id: 1338,
        rowNumber: 7,
        seatNumber: 32,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_7.value,
        status: "free",
      },
      {
        id: 1339,
        rowNumber: 7,
        seatNumber: 33,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_7.value,
        status: "free",
      },
      {
        id: 1340,
        rowNumber: 7,
        seatNumber: 34,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_7.value,
        status: "free",
      },
      {
        id: 1341,
        rowNumber: 7,
        seatNumber: 35,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_7.value,
        status: "free",
      },
      {
        id: 1342,
        rowNumber: 7,
        seatNumber: 36,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_7.value,
        status: "free",
      },
    ],

    /* row 8 */
    [
      {
        id: 1343,
        rowNumber: 8,
        seatNumber: 1,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_8.value,
        status: "free",
      },
      {
        id: 1344,
        rowNumber: 8,
        seatNumber: 2,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_8.value,
        status: "free",
      },
      {
        id: 1345,
        rowNumber: 8,
        seatNumber: 3,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_8.value,
        status: "booked",
      },
      {
        id: 1346,
        rowNumber: 8,
        seatNumber: 4,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_8.value,
        status: "booked",
      },
      {
        id: 1347,
        rowNumber: 8,
        seatNumber: 5,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_8.value,
        status: "booked",
      },
      {
        id: 1348,
        rowNumber: 8,
        seatNumber: 6,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_8.value,
        status: "booked",
      },
      {
        id: 1349,
        rowNumber: 8,
        seatNumber: 7,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_8.value,
        status: "free",
      },
      {
        id: 1350,
        rowNumber: 8,
        seatNumber: 8,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_8.value,
        status: "free",
      },
      {
        id: 1351,
        rowNumber: 8,
        seatNumber: 9,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_8.value,
        status: "free",
      },
      {
        id: 1352,
        rowNumber: 8,
        seatNumber: 10,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_8.value,
        status: "free",
      },
      {
        id: 1353,
        rowNumber: 8,
        seatNumber: 11,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_8.value,
        status: "free",
      },
      {
        id: 1354,
        rowNumber: 8,
        seatNumber: 12,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_8.value,
        status: "free",
      },
      {
        id: 1355,
        rowNumber: 8,
        seatNumber: 13,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_8.value,
        status: "free",
      },
      {
        id: 1356,
        rowNumber: 8,
        seatNumber: 14,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_8.value,
        status: "free",
      },
      {
        id: 1357,
        rowNumber: 8,
        seatNumber: 15,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_8.value,
        status: "booked",
      },
      {
        id: 1358,
        rowNumber: 8,
        seatNumber: 16,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_8.value,
        status: "booked",
      },
      {
        id: 1359,
        rowNumber: 8,
        seatNumber: 17,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_8.value,
        status: "booked",
      },
      {
        id: 1360,
        rowNumber: 8,
        seatNumber: 18,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_8.value,
        status: "booked",
      },
      {
        id: 1361,
        rowNumber: 8,
        seatNumber: 19,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_8.value,
        status: "booked",
      },
      {
        id: 1362,
        rowNumber: 8,
        seatNumber: 20,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_8.value,
        status: "booked",
      },
      {
        id: 1363,
        rowNumber: 8,
        seatNumber: 21,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_8.value,
        status: "free",
      },
      {
        id: 1364,
        rowNumber: 8,
        seatNumber: 22,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_8.value,
        status: "free",
      },
      {
        id: 1365,
        rowNumber: 8,
        seatNumber: 23,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_8.value,
        status: "free",
      },
      {
        id: 1366,
        rowNumber: 8,
        seatNumber: 24,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_8.value,
        status: "free",
      },
      {
        id: 1367,
        rowNumber: 8,
        seatNumber: 25,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_8.value,
        status: "free",
      },
      {
        id: 1368,
        rowNumber: 8,
        seatNumber: 26,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_8.value,
        status: "free",
      },
      {
        id: 1369,
        rowNumber: 8,
        seatNumber: 27,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_8.value,
        status: "free",
      },
      {
        id: 1370,
        rowNumber: 8,
        seatNumber: 28,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_8.value,
        status: "free",
      },
      {
        id: 1371,
        rowNumber: 8,
        seatNumber: 29,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_8.value,
        status: "free",
      },
      {
        id: 1372,
        rowNumber: 8,
        seatNumber: 30,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_8.value,
        status: "free",
      },
      {
        id: 1373,
        rowNumber: 8,
        seatNumber: 31,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_8.value,
        status: "free",
      },
      {
        id: 1374,
        rowNumber: 8,
        seatNumber: 32,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_8.value,
        status: "free",
      },
      {
        id: 1375,
        rowNumber: 8,
        seatNumber: 33,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_8.value,
        status: "free",
      },
      {
        id: 1376,
        rowNumber: 8,
        seatNumber: 34,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_8.value,
        status: "free",
      },
    ],

    /* row 9 */
    [
      {
        id: 1377,
        rowNumber: 9,
        seatNumber: 1,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_9.value,
        status: "free",
      },
      {
        id: 1378,
        rowNumber: 9,
        seatNumber: 2,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_9.value,
        status: "free",
      },
      {
        id: 1379,
        rowNumber: 9,
        seatNumber: 3,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_9.value,
        status: "free",
      },
      {
        id: 1380,
        rowNumber: 9,
        seatNumber: 4,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_9.value,
        status: "free",
      },
      {
        id: 1381,
        rowNumber: 9,
        seatNumber: 5,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_9.value,
        status: "free",
      },
      {
        id: 1382,
        rowNumber: 9,
        seatNumber: 6,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_9.value,
        status: "free",
      },
      {
        id: 1383,
        rowNumber: 9,
        seatNumber: 7,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_9.value,
        status: "free",
      },
      {
        id: 1384,
        rowNumber: 9,
        seatNumber: 8,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_9.value,
        status: "free",
      },
      {
        id: 1385,
        rowNumber: 9,
        seatNumber: 9,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_9.value,
        status: "free",
      },
      {
        id: 1386,
        rowNumber: 9,
        seatNumber: 10,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_9.value,
        status: "free",
      },
      {
        id: 1387,
        rowNumber: 9,
        seatNumber: 11,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_9.value,
        status: "free",
      },
      {
        id: 1388,
        rowNumber: 9,
        seatNumber: 12,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_9.value,
        status: "free",
      },
      {
        id: 1389,
        rowNumber: 9,
        seatNumber: 13,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_9.value,
        status: "free",
      },
      {
        id: 1390,
        rowNumber: 9,
        seatNumber: 14,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_9.value,
        status: "free",
      },
      {
        id: 1391,
        rowNumber: 9,
        seatNumber: 15,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_9.value,
        status: "free",
      },
      {
        id: 1392,
        rowNumber: 9,
        seatNumber: 16,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_9.value,
        status: "free",
      },
      {
        id: 1393,
        rowNumber: 9,
        seatNumber: 17,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_9.value,
        status: "free",
      },
      {
        id: 1394,
        rowNumber: 9,
        seatNumber: 18,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_9.value,
        status: "free",
      },
      {
        id: 1395,
        rowNumber: 9,
        seatNumber: 19,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_9.value,
        status: "free",
      },
      {
        id: 1396,
        rowNumber: 9,
        seatNumber: 20,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_9.value,
        status: "free",
      },
      {
        id: 1397,
        rowNumber: 9,
        seatNumber: 21,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_9.value,
        status: "free",
      },
      {
        id: 1398,
        rowNumber: 9,
        seatNumber: 22,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_9.value,
        status: "free",
      },
      {
        id: 1399,
        rowNumber: 9,
        seatNumber: 23,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_9.value,
        status: "free",
      },
      {
        id: 1400,
        rowNumber: 9,
        seatNumber: 24,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_9.value,
        status: "free",
      },
      {
        id: 1401,
        rowNumber: 9,
        seatNumber: 25,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_9.value,
        status: "free",
      },
      {
        id: 1402,
        rowNumber: 9,
        seatNumber: 26,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_9.value,
        status: "free",
      },
      {
        id: 1403,
        rowNumber: 9,
        seatNumber: 27,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_9.value,
        status: "free",
      },
      {
        id: 1404,
        rowNumber: 9,
        seatNumber: 28,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_9.value,
        status: "booked",
      },
      {
        id: 1405,
        rowNumber: 9,
        seatNumber: 29,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_9.value,
        status: "booked",
      },
      {
        id: 1406,
        rowNumber: 9,
        seatNumber: 30,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_9.value,
        status: "free",
      },
      {
        id: 1407,
        rowNumber: 9,
        seatNumber: 31,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_9.value,
        status: "free",
      },
      {
        id: 1408,
        rowNumber: 9,
        seatNumber: 32,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_9.value,
        status: "free",
      },
      {
        id: 1409,
        rowNumber: 9,
        seatNumber: 33,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_9.value,
        status: "free",
      },
      {
        id: 1410,
        rowNumber: 9,
        seatNumber: 34,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_9.value,
        status: "free",
      },
    ],

    /* row 10 */
    [
      {
        id: 1411,
        rowNumber: 10,
        seatNumber: 1,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_10.value,
        status: "free",
      },
      {
        id: 1412,
        rowNumber: 10,
        seatNumber: 2,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_10.value,
        status: "free",
      },
      {
        id: 1413,
        rowNumber: 10,
        seatNumber: 3,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_10.value,
        status: "free",
      },
      {
        id: 1414,
        rowNumber: 10,
        seatNumber: 4,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_10.value,
        status: "free",
      },
      {
        id: 1415,
        rowNumber: 10,
        seatNumber: 5,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_10.value,
        status: "free",
      },
      {
        id: 1416,
        rowNumber: 10,
        seatNumber: 6,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_10.value,
        status: "free",
      },
      {
        id: 1417,
        rowNumber: 10,
        seatNumber: 7,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_10.value,
        status: "booked",
      },
      {
        id: 1418,
        rowNumber: 10,
        seatNumber: 8,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_10.value,
        status: "booked",
      },
      null,
      {
        id: 1419,
        rowNumber: 10,
        seatNumber: 9,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_10.value,
        status: "free",
      },
      {
        id: 1420,
        rowNumber: 10,
        seatNumber: 10,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_10.value,
        status: "free",
      },
      {
        id: 1421,
        rowNumber: 10,
        seatNumber: 11,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_10.value,
        status: "free",
      },
      {
        id: 1422,
        rowNumber: 10,
        seatNumber: 12,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_10.value,
        status: "free",
      },
      {
        id: 1423,
        rowNumber: 10,
        seatNumber: 13,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_10.value,
        status: "free",
      },
      {
        id: 1424,
        rowNumber: 10,
        seatNumber: 14,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_10.value,
        status: "free",
      },
      {
        id: 1425,
        rowNumber: 10,
        seatNumber: 15,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_10.value,
        status: "free",
      },
      {
        id: 1426,
        rowNumber: 10,
        seatNumber: 16,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_10.value,
        status: "free",
      },
      {
        id: 1427,
        rowNumber: 10,
        seatNumber: 17,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_10.value,
        status: "free",
      },
      {
        id: 1428,
        rowNumber: 10,
        seatNumber: 18,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_10.value,
        status: "free",
      },
      {
        id: 1429,
        rowNumber: 10,
        seatNumber: 19,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_10.value,
        status: "free",
      },
      {
        id: 1430,
        rowNumber: 10,
        seatNumber: 20,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_10.value,
        status: "free",
      },
      {
        id: 1431,
        rowNumber: 10,
        seatNumber: 21,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_10.value,
        status: "free",
      },
      {
        id: 1432,
        rowNumber: 10,
        seatNumber: 22,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_10.value,
        status: "free",
      },
      {
        id: 1433,
        rowNumber: 10,
        seatNumber: 23,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_10.value,
        status: "free",
      },
      {
        id: 1434,
        rowNumber: 10,
        seatNumber: 24,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_10.value,
        status: "free",
      },
      {
        id: 1435,
        rowNumber: 10,
        seatNumber: 25,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_10.value,
        status: "free",
      },
      {
        id: 1436,
        rowNumber: 10,
        seatNumber: 26,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_10.value,
        status: "free",
      },
      null,
      {
        id: 1437,
        rowNumber: 10,
        seatNumber: 27,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_10.value,
        status: "free",
      },
      {
        id: 1438,
        rowNumber: 10,
        seatNumber: 28,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_10.value,
        status: "free",
      },
      {
        id: 1439,
        rowNumber: 10,
        seatNumber: 29,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_10.value,
        status: "free",
      },
      {
        id: 1440,
        rowNumber: 10,
        seatNumber: 30,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_10.value,
        status: "free",
      },
      {
        id: 1441,
        rowNumber: 10,
        seatNumber: 31,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_10.value,
        status: "free",
      },
      {
        id: 1442,
        rowNumber: 10,
        seatNumber: 32,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_10.value,
        status: "free",
      },
      {
        id: 1443,
        rowNumber: 10,
        seatNumber: 33,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_10.value,
        status: "free",
      },
      {
        id: 1444,
        rowNumber: 10,
        seatNumber: 34,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_10.value,
        status: "free",
      },
    ],

    /* row 11 */
    [
      {
        id: 1445,
        rowNumber: 11,
        seatNumber: 1,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_11.value,
        status: "free",
      },
      {
        id: 1446,
        rowNumber: 11,
        seatNumber: 2,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_11.value,
        status: "free",
      },
      {
        id: 1447,
        rowNumber: 11,
        seatNumber: 3,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_11.value,
        status: "free",
      },
      {
        id: 1448,
        rowNumber: 11,
        seatNumber: 4,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_11.value,
        status: "free",
      },
      {
        id: 1449,
        rowNumber: 11,
        seatNumber: 5,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_11.value,
        status: "free",
      },
      {
        id: 1450,
        rowNumber: 11,
        seatNumber: 6,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_11.value,
        status: "free",
      },
      {
        id: 1451,
        rowNumber: 11,
        seatNumber: 7,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_11.value,
        status: "free",
      },
      {
        id: 1452,
        rowNumber: 11,
        seatNumber: 8,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_11.value,
        status: "free",
      },
      null,
      null,
      null,
      {
        id: 1453,
        rowNumber: 11,
        seatNumber: 9,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_11.value,
        status: "booked",
      },
      {
        id: 1454,
        rowNumber: 11,
        seatNumber: 10,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_11.value,
        status: "booked",
      },
      {
        id: 1455,
        rowNumber: 11,
        seatNumber: 11,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_11.value,
        status: "free",
      },
      {
        id: 1456,
        rowNumber: 11,
        seatNumber: 12,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_11.value,
        status: "free",
      },
      {
        id: 1457,
        rowNumber: 11,
        seatNumber: 13,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_11.value,
        status: "free",
      },
      {
        id: 1458,
        rowNumber: 11,
        seatNumber: 14,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_11.value,
        status: "free",
      },
      {
        id: 1459,
        rowNumber: 11,
        seatNumber: 15,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_11.value,
        status: "free",
      },
      {
        id: 1460,
        rowNumber: 11,
        seatNumber: 16,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_11.value,
        status: "free",
      },
      {
        id: 1461,
        rowNumber: 11,
        seatNumber: 17,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_11.value,
        status: "free",
      },
      {
        id: 1462,
        rowNumber: 11,
        seatNumber: 18,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_11.value,
        status: "free",
      },
      {
        id: 1463,
        rowNumber: 11,
        seatNumber: 19,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_11.value,
        status: "free",
      },
      {
        id: 1464,
        rowNumber: 11,
        seatNumber: 20,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_11.value,
        status: "free",
      },
      {
        id: 1465,
        rowNumber: 11,
        seatNumber: 21,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_11.value,
        status: "free",
      },
      {
        id: 1466,
        rowNumber: 11,
        seatNumber: 22,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_11.value,
        status: "free",
      },
      {
        id: 1467,
        rowNumber: 11,
        seatNumber: 23,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_11.value,
        status: "free",
      },
      {
        id: 1468,
        rowNumber: 11,
        seatNumber: 24,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_11.value,
        status: "free",
      },
      null,
      null,
      null,
      {
        id: 1469,
        rowNumber: 11,
        seatNumber: 25,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_11.value,
        status: "free",
      },
      {
        id: 1470,
        rowNumber: 11,
        seatNumber: 26,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_11.value,
        status: "free",
      },
      {
        id: 1471,
        rowNumber: 11,
        seatNumber: 27,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_11.value,
        status: "free",
      },
      {
        id: 1472,
        rowNumber: 11,
        seatNumber: 28,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_11.value,
        status: "free",
      },
      {
        id: 1473,
        rowNumber: 11,
        seatNumber: 29,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_11.value,
        status: "free",
      },
      {
        id: 1474,
        rowNumber: 11,
        seatNumber: 30,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_11.value,
        status: "free",
      },
      {
        id: 1475,
        rowNumber: 11,
        seatNumber: 31,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_11.value,
        status: "free",
      },
      {
        id: 1476,
        rowNumber: 11,
        seatNumber: 32,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_11.value,
        status: "free",
      },
    ],

    /* row 12 */
    [
      {
        id: 1477,
        rowNumber: 12,
        seatNumber: 1,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_12.value,
        status: "free",
      },
      {
        id: 1478,
        rowNumber: 12,
        seatNumber: 2,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_12.value,
        status: "free",
      },
      {
        id: 1479,
        rowNumber: 12,
        seatNumber: 3,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_12.value,
        status: "free",
      },
      {
        id: 1480,
        rowNumber: 12,
        seatNumber: 4,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_12.value,
        status: "free",
      },
      {
        id: 1481,
        rowNumber: 12,
        seatNumber: 5,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_12.value,
        status: "free",
      },
      {
        id: 1482,
        rowNumber: 12,
        seatNumber: 6,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_12.value,
        status: "free",
      },
      {
        id: 1483,
        rowNumber: 12,
        seatNumber: 7,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_12.value,
        status: "free",
      },
      {
        id: 1484,
        rowNumber: 12,
        seatNumber: 8,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_12.value,
        status: "free",
      },
      null,
      null,
      null,
      null,
      null,
      {
        id: 1485,
        rowNumber: 12,
        seatNumber: 9,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_12.value,
        status: "free",
      },
      {
        id: 1486,
        rowNumber: 12,
        seatNumber: 10,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_12.value,
        status: "free",
      },
      {
        id: 1487,
        rowNumber: 12,
        seatNumber: 11,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_12.value,
        status: "free",
      },
      {
        id: 1488,
        rowNumber: 12,
        seatNumber: 12,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_12.value,
        status: "free",
      },
      {
        id: 1489,
        rowNumber: 12,
        seatNumber: 13,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_12.value,
        status: "free",
      },
      {
        id: 1490,
        rowNumber: 12,
        seatNumber: 14,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_12.value,
        status: "free",
      },
      {
        id: 1491,
        rowNumber: 12,
        seatNumber: 15,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_12.value,
        status: "free",
      },
      {
        id: 1492,
        rowNumber: 12,
        seatNumber: 16,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_12.value,
        status: "free",
      },
      {
        id: 1493,
        rowNumber: 12,
        seatNumber: 17,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_12.value,
        status: "free",
      },
      {
        id: 1494,
        rowNumber: 12,
        seatNumber: 18,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_12.value,
        status: "free",
      },
      {
        id: 1495,
        rowNumber: 12,
        seatNumber: 19,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_12.value,
        status: "booked",
      },
      {
        id: 1496,
        rowNumber: 12,
        seatNumber: 20,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_12.value,
        status: "booked",
      },
      {
        id: 1497,
        rowNumber: 12,
        seatNumber: 21,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_12.value,
        status: "booked",
      },
      {
        id: 1498,
        rowNumber: 12,
        seatNumber: 22,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_12.value,
        status: "booked",
      },
      null,
      null,
      null,
      null,
      null,
      {
        id: 1499,
        rowNumber: 12,
        seatNumber: 23,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_12.value,
        status: "free",
      },
      {
        id: 1500,
        rowNumber: 12,
        seatNumber: 24,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_12.value,
        status: "free",
      },
      {
        id: 1501,
        rowNumber: 12,
        seatNumber: 25,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_12.value,
        status: "free",
      },
      {
        id: 1502,
        rowNumber: 12,
        seatNumber: 26,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_12.value,
        status: "free",
      },
      {
        id: 1503,
        rowNumber: 12,
        seatNumber: 27,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_12.value,
        status: "free",
      },
      {
        id: 1504,
        rowNumber: 12,
        seatNumber: 28,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_12.value,
        status: "free",
      },
      {
        id: 1505,
        rowNumber: 12,
        seatNumber: 29,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_12.value,
        status: "free",
      },
      {
        id: 1506,
        rowNumber: 12,
        seatNumber: 30,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_12.value,
        status: "free",
      },
    ],

    /* row 13 */
    [
      {
        id: 1507,
        rowNumber: 13,
        seatNumber: 1,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_13.value,
        status: "nonSale",
      },
      {
        id: 1508,
        rowNumber: 13,
        seatNumber: 2,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_13.value,
        status: "nonSale",
      },
      {
        id: 1509,
        rowNumber: 13,
        seatNumber: 3,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_13.value,
        status: "nonSale",
      },
      {
        id: 1510,
        rowNumber: 13,
        seatNumber: 4,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_13.value,
        status: "nonSale",
      },
      {
        id: 1511,
        rowNumber: 13,
        seatNumber: 5,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_13.value,
        status: "nonSale",
      },
      {
        id: 1512,
        rowNumber: 13,
        seatNumber: 6,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_13.value,
        status: "nonSale",
      },
      {
        id: 1513,
        rowNumber: 13,
        seatNumber: 7,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_13.value,
        status: "nonSale",
      },
      {
        id: 1514,
        rowNumber: 13,
        seatNumber: 8,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_13.value,
        status: "nonSale",
      },
      null,
      {
        id: 1515,
        rowNumber: 13,
        seatNumber: 9,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_13.value,
        status: "nonSale",
      },
      {
        id: 1516,
        rowNumber: 13,
        seatNumber: 10,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_13.value,
        status: "nonSale",
      },
      {
        id: 1517,
        rowNumber: 13,
        seatNumber: 11,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_13.value,
        status: "nonSale",
      },
      {
        id: 1518,
        rowNumber: 13,
        seatNumber: 12,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_13.value,
        status: "nonSale",
      },
      {
        id: 1519,
        rowNumber: 13,
        seatNumber: 13,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_13.value,
        status: "nonSale",
      },
      {
        id: 1520,
        rowNumber: 13,
        seatNumber: 14,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_13.value,
        status: "nonSale",
      },
      {
        id: 1521,
        rowNumber: 13,
        seatNumber: 15,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_13.value,
        status: "nonSale",
      },
      {
        id: 1522,
        rowNumber: 13,
        seatNumber: 16,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_13.value,
        status: "nonSale",
      },
      {
        id: 1523,
        rowNumber: 13,
        seatNumber: 17,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_13.value,
        status: "nonSale",
      },
      {
        id: 1524,
        rowNumber: 13,
        seatNumber: 18,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_13.value,
        status: "nonSale",
      },
      {
        id: 1525,
        rowNumber: 13,
        seatNumber: 19,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_13.value,
        status: "nonSale",
      },
      {
        id: 1526,
        rowNumber: 13,
        seatNumber: 20,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_13.value,
        status: "nonSale",
      },
      {
        id: 1527,
        rowNumber: 13,
        seatNumber: 21,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_13.value,
        status: "nonSale",
      },
      {
        id: 1528,
        rowNumber: 13,
        seatNumber: 22,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_13.value,
        status: "nonSale",
      },
      {
        id: 1529,
        rowNumber: 13,
        seatNumber: 23,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_13.value,
        status: "nonSale",
      },
      {
        id: 1530,
        rowNumber: 13,
        seatNumber: 24,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_13.value,
        status: "nonSale",
      },
      {
        id: 1531,
        rowNumber: 13,
        seatNumber: 25,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_13.value,
        status: "nonSale",
      },
      {
        id: 1532,
        rowNumber: 13,
        seatNumber: 26,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_13.value,
        status: "nonSale",
      },
      null,
      {
        id: 1533,
        rowNumber: 13,
        seatNumber: 27,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_13.value,
        status: "nonSale",
      },
      {
        id: 1534,
        rowNumber: 13,
        seatNumber: 28,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_13.value,
        status: "nonSale",
      },
      {
        id: 1535,
        rowNumber: 13,
        seatNumber: 29,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_13.value,
        status: "nonSale",
      },
      {
        id: 1536,
        rowNumber: 13,
        seatNumber: 30,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_13.value,
        status: "nonSale",
      },
      {
        id: 1537,
        rowNumber: 13,
        seatNumber: 31,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_13.value,
        status: "nonSale",
      },
      {
        id: 1538,
        rowNumber: 13,
        seatNumber: 32,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_13.value,
        status: "nonSale",
      },
      {
        id: 1539,
        rowNumber: 13,
        seatNumber: 33,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_13.value,
        status: "nonSale",
      },
      {
        id: 1540,
        rowNumber: 13,
        seatNumber: 34,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_13.value,
        status: "nonSale",
      },
    ],

    /* row 14 */
    [
      {
        id: 1541,
        rowNumber: 14,
        seatNumber: 1,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_14.value,
        status: "free",
      },
      {
        id: 1542,
        rowNumber: 14,
        seatNumber: 2,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_14.value,
        status: "free",
      },
      {
        id: 1543,
        rowNumber: 14,
        seatNumber: 3,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_14.value,
        status: "free",
      },
      {
        id: 1544,
        rowNumber: 14,
        seatNumber: 4,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_14.value,
        status: "free",
      },
      {
        id: 1545,
        rowNumber: 14,
        seatNumber: 5,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_14.value,
        status: "pending",
      },
      {
        id: 1546,
        rowNumber: 14,
        seatNumber: 6,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_14.value,
        status: "pending",
      },
      {
        id: 1547,
        rowNumber: 14,
        seatNumber: 7,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_14.value,
        status: "pending",
      },
      {
        id: 1548,
        rowNumber: 14,
        seatNumber: 8,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_14.value,
        status: "free",
      },
      {
        id: 1549,
        rowNumber: 14,
        seatNumber: 9,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_14.value,
        status: "free",
      },
      {
        id: 1550,
        rowNumber: 14,
        seatNumber: 10,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_14.value,
        status: "free",
      },
      {
        id: 1551,
        rowNumber: 14,
        seatNumber: 11,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_14.value,
        status: "free",
      },
      {
        id: 1552,
        rowNumber: 14,
        seatNumber: 12,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_14.value,
        status: "free",
      },
      {
        id: 1553,
        rowNumber: 14,
        seatNumber: 13,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_14.value,
        status: "free",
      },
      {
        id: 1554,
        rowNumber: 14,
        seatNumber: 14,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_14.value,
        status: "free",
      },
      {
        id: 1555,
        rowNumber: 14,
        seatNumber: 15,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_14.value,
        status: "free",
      },
      {
        id: 1556,
        rowNumber: 14,
        seatNumber: 16,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_14.value,
        status: "free",
      },
      {
        id: 1557,
        rowNumber: 14,
        seatNumber: 17,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_14.value,
        status: "free",
      },
      {
        id: 1558,
        rowNumber: 14,
        seatNumber: 18,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_14.value,
        status: "free",
      },
      {
        id: 1559,
        rowNumber: 14,
        seatNumber: 19,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_14.value,
        status: "free",
      },
      {
        id: 1560,
        rowNumber: 14,
        seatNumber: 20,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_14.value,
        status: "free",
      },
      {
        id: 1561,
        rowNumber: 14,
        seatNumber: 21,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_14.value,
        status: "free",
      },
      {
        id: 1562,
        rowNumber: 14,
        seatNumber: 22,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_14.value,
        status: "free",
      },
      {
        id: 1563,
        rowNumber: 14,
        seatNumber: 23,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_14.value,
        status: "free",
      },
      {
        id: 1564,
        rowNumber: 14,
        seatNumber: 24,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_14.value,
        status: "free",
      },
      {
        id: 1565,
        rowNumber: 14,
        seatNumber: 25,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_14.value,
        status: "free",
      },
      {
        id: 1566,
        rowNumber: 14,
        seatNumber: 26,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_14.value,
        status: "free",
      },
      {
        id: 1567,
        rowNumber: 14,
        seatNumber: 27,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_14.value,
        status: "free",
      },
      {
        id: 1568,
        rowNumber: 14,
        seatNumber: 28,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_14.value,
        status: "free",
      },
      {
        id: 1569,
        rowNumber: 14,
        seatNumber: 29,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_14.value,
        status: "free",
      },
      {
        id: 1570,
        rowNumber: 14,
        seatNumber: 30,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_14.value,
        status: "free",
      },
    ],

    /* row 15 */
    [
      {
        id: 1571,
        rowNumber: 15,
        seatNumber: 1,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_15.value,
        status: "booked",
      },
      {
        id: 1572,
        rowNumber: 15,
        seatNumber: 2,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_15.value,
        status: "booked",
      },
      {
        id: 1573,
        rowNumber: 15,
        seatNumber: 3,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_15.value,
        status: "booked",
      },
      {
        id: 1574,
        rowNumber: 15,
        seatNumber: 4,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_15.value,
        status: "booked",
      },
      {
        id: 1575,
        rowNumber: 15,
        seatNumber: 5,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_15.value,
        status: "booked",
      },
      {
        id: 1576,
        rowNumber: 15,
        seatNumber: 6,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_15.value,
        status: "booked",
      },
      {
        id: 1577,
        rowNumber: 15,
        seatNumber: 7,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_15.value,
        status: "booked",
      },
      {
        id: 1578,
        rowNumber: 15,
        seatNumber: 8,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_15.value,
        status: "booked",
      },
      {
        id: 1579,
        rowNumber: 15,
        seatNumber: 9,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_15.value,
        status: "booked",
      },
      {
        id: 1580,
        rowNumber: 15,
        seatNumber: 10,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_15.value,
        status: "booked",
      },
      {
        id: 1581,
        rowNumber: 15,
        seatNumber: 11,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_15.value,
        status: "booked",
      },
      {
        id: 1582,
        rowNumber: 15,
        seatNumber: 12,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_15.value,
        status: "booked",
      },
      {
        id: 1583,
        rowNumber: 15,
        seatNumber: 13,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_15.value,
        status: "booked",
      },
      {
        id: 1584,
        rowNumber: 15,
        seatNumber: 14,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_15.value,
        status: "booked",
      },
      {
        id: 1585,
        rowNumber: 15,
        seatNumber: 15,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_15.value,
        status: "booked",
      },
      {
        id: 1586,
        rowNumber: 15,
        seatNumber: 16,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_15.value,
        status: "booked",
      },
      {
        id: 1587,
        rowNumber: 15,
        seatNumber: 17,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_15.value,
        status: "booked",
      },
      {
        id: 1588,
        rowNumber: 15,
        seatNumber: 18,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_15.value,
        status: "booked",
      },
      {
        id: 1589,
        rowNumber: 15,
        seatNumber: 19,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_15.value,
        status: "booked",
      },
      {
        id: 1590,
        rowNumber: 15,
        seatNumber: 20,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_15.value,
        status: "booked",
      },
      {
        id: 1591,
        rowNumber: 15,
        seatNumber: 21,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_15.value,
        status: "booked",
      },
      {
        id: 1592,
        rowNumber: 15,
        seatNumber: 22,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_15.value,
        status: "booked",
      },
      {
        id: 1593,
        rowNumber: 15,
        seatNumber: 23,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_15.value,
        status: "booked",
      },
      {
        id: 1594,
        rowNumber: 15,
        seatNumber: 24,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_15.value,
        status: "booked",
      },
      {
        id: 1595,
        rowNumber: 15,
        seatNumber: 25,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_15.value,
        status: "booked",
      },
      {
        id: 1596,
        rowNumber: 15,
        seatNumber: 26,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_15.value,
        status: "booked",
      },
      {
        id: 1597,
        rowNumber: 15,
        seatNumber: 27,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_15.value,
        status: "booked",
      },
      {
        id: 1598,
        rowNumber: 15,
        seatNumber: 28,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_15.value,
        status: "booked",
      },
      {
        id: 1599,
        rowNumber: 15,
        seatNumber: 29,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_15.value,
        status: "booked",
      },
      {
        id: 1600,
        rowNumber: 15,
        seatNumber: 30,
        seatPrice: WEST_MALL_PRICES.PRICE_ROW_15.value,
        status: "booked",
      },
    ],
  ],
};
